export const labels = {
  auth: {
    signIn: "Sign In",
    signingIn: "Signing in...",
    signOut: "Sign Out",
    email: "Email",
    password: "Password",
    invalidCredentials: "Invalid email or password.",
    emailPlaceholder: "name@email.com",
  },
  nav: {
    brand: "Gamifikasi",
    home: "Home",
    learn: "Learning",
    chat: "AI Chat",
    dashboard: "Dashboard",
    levels: "Levels",
    users: "Users",
    breadcrumb: {
      dashboard: "Dashboard",
      users: "Users",
      ranking: "Ranking",
      newUser: "New User",
      editUser: "Edit User",
      levels: "Levels",
      groups: "Groups",
      newGroup: "New Group",
      content: "Content",
      addContent: "Add Content",
      newMaterial: "New Material",
      newQuestion: "New Question",
      editItem: "Edit Item",
      level: "Level",
      group: "Group",
      home: "Home",
      learning: "Learning",
      aiChat: "AI Chat",
      speaking: "Speaking",
      reading: "Reading",
      listening: "Listening",
      multipleChoice: "Multiple Choice",
      essay: "Essay",
      speechRecognition: "Speech Recognition",
      profile: "Profile",
      testimonials: "Testimonials",
    },
    adminPanel: "Admin Panel",
    learning: "Learning Hub",
    menu: "Menu",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    openMenu: "Open menu",
    openSteps: "Steps",
    closeSteps: "Close steps",
    defaultStudent: "Student",
    ranking: "Ranking",
    badges: "Badges",
    challenges: "Challenges",
    rewards: "Rewards",
    testimonials: "Testimonials",
    points: (pts: number) => `${pts} pts`,
  },
  theme: {
    toggle: "Theme",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  levels: {
    BASIC: "Basic",
    INTERMEDIATE: "Intermediate",
    HARD: "Advanced",
  },
  status: {
    notStarted: "Not Started",
    inProgress: "In Progress",
    completed: "Completed",
    published: "Published",
    draft: "Draft",
  },
  common: {
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    title: "Title",
    content: "Content",
    correct: "Correct",
    search: "Search",
  },
  admin: {
    dashboardTitle: "Admin Dashboard",
    dashboardDescription:
      "Overview of students, content, and learning levels.",
    totalStudents: "Total Students",
    totalGroups: "Total Groups",
    totalQuestions: "Total Questions",
    manageLevels: "Manage Levels",
    groupsPublished: (total: number, published: number) =>
      `${total} groups · ${published} published`,
    learningLevels: "Learning Levels",
    manageContent: "Manage Content",
    levelPrefix: (name: string) => `Level: ${name}`,
    addNewGroup: "Add New Group",
    groupTitle: "Group Title",
    premiumContent: "Premium content",
    premiumContentHint: "Requires proficiency achievement to unlock for students.",
    groupTitlePlaceholder: "Introduction to Variables",
    autoOrder: (order: number) => `Auto order: ${order}`,
    saveTitle: "Save title",
    unsavedTitleHint: "Title changed — tap the check button to save.",
    editorViewMode: "Editor view mode",
    noGroups: "No groups yet. Add a new group.",
    materialsCount: (materials: number, questions: number) =>
      `${materials} materials · ${questions} questions`,
    groupContents: "Contents",
    showContents: "Show contents",
    hideContents: "Hide contents",
    groupContentsEmpty: "No content items in this group yet.",
    publish: "Publish",
    unpublish: "Unpublish",
    tabMaterials: "Materials",
    tabQuestions: "Questions",
    addContent: "Add Content",
    chooseContentType: "Choose what you want to create",
    createMaterial: "Create Material",
    createQuestion: "Create Question",
    noMaterialsYet: "No materials yet. Create your first material.",
    noQuestionsYet: "No questions yet. Create your first question.",
    contentSummary: (materials: number, questions: number) =>
      `${materials} materials · ${questions} questions`,
    saveMaterial: "Save Material",
    addMaterial: "Add Material",
    newMaterial: "New Material",
    materialPlaceholder: "Material content...",
    addQuestion: "Add Question",
    questionPlaceholder: "Question text",
    optionA: "Option A",
    optionB: "Option B",
    optionC: "Option C",
    optionD: "Option D",
    correctAnswer: "Correct Answer",
    explanationOptional: "Explanation (optional)",
    addItem: "Add Item",
    pickType: "What do you want to add?",
    typeMaterial: "Material",
    typeMaterialDesc: "Rich text lesson with images and links",
    typeQuestion: "Question",
    typeQuestionDesc:
      "One question item with multiple sub-questions (skills, formats, weights). Total weight must equal 100%.",
    pickSkill: "Choose skill type",
    skillSpeaking: "Speaking",
    skillReading: "Reading",
    skillWriting: "Writing",
    skillListening: "Listening",
    pickFormat: "Choose answer format",
    formatMcq: "Multiple Choice (A–D)",
    formatYesNo: "Yes / No",
    formatEssay: "Essay",
    formatSpeech: "Speech Recognition",
    addSubQuestion: "Add sub-question",
    removeSubQuestion: "Remove",
    subQuestionOf: (current: number, total: number) =>
      `Sub-question ${current} of ${total}`,
    weightPercent: "Weight (%)",
    totalWeight: (total: number) => `Total weight: ${total}%`,
    weightNeedMore: (need: number) => `Need ${need}% more to reach 100%`,
    weightOver: (over: number) => `${over}% over 100% — adjust weights`,
    weightValid: "Weights total 100%",
    moveUp: "Move up",
    moveDown: "Move down",
    subQuestionsCount: (count: number) => `${count} sub-questions`,
    expectedSpeech: "Expected sentence (for speech match)",
    uploadAudio: "Upload audio file",
    uploadImage: "Upload image",
    materialPreview: "Preview",
    questionTextLabel: "Question",
    answerOptions: "Answer options",
    correctBadge: "Correct",
    explanationLabel: "Explanation",
    materialPreviewEmpty: "Start writing to see the preview here.",
    editorLabel: "Editor",
    showDetails: "Show details",
    hideDetails: "Hide details",
    showPreview: "Show preview",
    hidePreview: "Hide preview",
    essayRubric: "Essay rubric (optional)",
    contentItems: (count: number) => `${count} items in sequence`,
    noItemsYet: "No content yet. Add your first material or question.",
    usersTitle: "User Management",
    usersDescription: "Manage student and admin accounts for login.",
    testimonialsTitle: "Student Testimonials",
    testimonialsDescription:
      "Reviews submitted after students complete a learning group.",
    testimonialStudent: "Student",
    testimonialLevel: "Level",
    testimonialGroup: "Group",
    testimonialScore: "Score",
    testimonialRating: "Rating",
    testimonialText: "Testimonial",
    testimonialDate: "Submitted",
    testimonialAiFeedback: "AI feedback",
    testimonialEmpty: "No testimonials submitted yet.",
    testimonialViewDetails: "View details",
    testimonialSearchPlaceholder: "Search by student name…",
    rankingTitle: "Student Rankings",
    rankingDescription:
      "View all student leaderboard positions, tiers, and points.",
    rankedStudents: "Ranked Students",
    topScore: "Top Score",
    addUser: "Add User",
    editUser: "Edit User",
    noUsersYet: "No users yet. Add your first user.",
    searchUsers: "Search by name, email, phone, school, or NIS/NIM...",
    filterAll: "All",
    filterStudents: "Students",
    filterAdmins: "Admins",
    accountSection: "Account",
    profileSection: "Personal Data",
    fullName: "Full Name",
    fullNamePlaceholder: "e.g. Budi Santoso",
    phone: "Phone Number",
    phonePlaceholder: "e.g. 081234567890",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    genderMale: "Male",
    genderFemale: "Female",
    genderUnset: "Not specified",
    institution: "School / Institution",
    institutionPlaceholder: "e.g. SMA Negeri 1 Jakarta",
    studentId: "NIS / NIM",
    studentIdPlaceholder: "e.g. NIS-2024001",
    userRole: "Role",
    userActive: "Active (can login)",
    userInactive: "Inactive",
    password: "Password",
    passwordPlaceholder: "Min. 6 characters",
    passwordOptional: "New password (leave blank to keep current)",
    points: "Points",
    deleteUserTitle: "Delete user?",
    deleteUserDescription: (name: string) =>
      `This will permanently delete ${name} and all their progress, answers, and chat history.`,
    requiredFieldHint: "Fields marked with * are required.",
    userCreated: "User created successfully.",
    userUpdated: "User updated successfully.",
    itemMaterial: "Material",
    itemQuestion: "Question",
    stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
    stepsNav: "Steps",
    groupComplete: "Group complete!",
    finishGroup: "Finish Group",
    finishGroupHint: "Submit your feedback to unlock the next group.",
    assessmentsSection: "Pretest & Posttest",
    assessmentsHint:
      "Students rate each statement 1–5 (1 = strongly disagree, 5 = strongly agree). Pretest appears before materials; posttest after all content is done.",
    pretest: "Pretest",
    posttest: "Posttest",
    addAssessmentQuestion: "Add question",
    assessmentQuestionPlaceholder: "e.g. I understand the topic of this group.",
    noPretestQuestions: "No pretest questions yet.",
    noPosttestQuestions: "No posttest questions yet.",
    assessmentScaleHint: "Students answer with a 1–5 slider only.",
    deleteAssessmentQuestion: "Delete question",
  },
  student: {
    welcome: (name: string) => `Welcome, ${name}!`,
    chooseLevel: "Choose a level to start or continue learning.",
    groupsCompleted: (completed: number, total: number) =>
      `${completed} groups completed of ${total} groups`,
    startLearning: "Start Learning",
    continueLearning: "Continue Learning",
    materialsProgress: (percent: number) => `${percent}% complete`,
    stepsProgress: (percent: number) => `${percent}% complete`,
    start: "Start",
    continue: "Continue",
    finishGroupHint: "Submit your feedback to unlock the next group.",
    unlockPrevious:
      "Complete the previous group first.",
    noPublishedGroups: "No published groups for this level yet.",
    backToLevel: "Back to Level",
    backToMaterials: "Back to Materials",
    noMaterials: "No materials yet. Return to the group list.",
    materialsNav: "Materials",
    previous: "Previous",
    next: "Next",
    takeQuiz: "Take Quiz",
    quizTitle: (title: string) => `Quiz: ${title}`,
    noQuestions: "No questions for this group yet.",
    questionOf: (current: number, total: number) =>
      `Question ${current} of ${total}`,
    correctAnswer: "Correct!",
    wrongAnswer: "Incorrect",
    correctAnswerIs: "Correct answer:",
    explanation: "Explanation",
    nextQuestion: "Next Question",
    viewResults: "View Results",
    quizComplete: "Complete!",
    completionScore: "Your score",
    completionScoreLabel: (percent: number) => `${percent}%`,
    aiCompletionFeedback: "AI Feedback",
    aiCompletionLoading: "Generating your personalized feedback…",
    testimonialTitle: "Share your experience",
    testimonialSubtitle:
      "Your testimonial is required before you can leave this page.",
    testimonialRatingLabel: "Rating",
    testimonialRatingRequired: "Please select a rating from 1 to 5 stars.",
    testimonialPlaceholder:
      "Tell us what you learned and how this group helped you…",
    testimonialRequired: "Testimonial is required to finish this group.",
    testimonialMinLength: "Please write at least 20 characters.",
    testimonialAlreadySubmitted: "You have already submitted a testimonial.",
    submitTestimonial: "Submit testimonial",
    testimonialSubmitting: "Submitting…",
    testimonialThankYou: "Thank you for your feedback!",
    scoreSummary: (score: number, total: number) =>
      `${score} of ${total} correct`,
    pointsAdded: (points: number) => `+${points} points added`,
    feedbackUnavailable: "Feedback unavailable.",
    feedbackLoadError: "Failed to load AI feedback.",
    chatTitle: "AI Chat",
    chatSubtitle:
      "Learning assistant to help you understand course materials.",
    chatPlaceholder: "Type your question...",
    chatSend: "Send",
    chatError: "Sorry, something went wrong. Please try again later.",
    aiAssistantTitle: "AI Assistant",
    aiAssistantOpen: "Open AI Assistant",
    aiAssistantClose: "Collapse AI Assistant",
    aiAssistantExpand: "Expand AI Assistant",
    stepsOpen: "Open learning steps",
    stepsExpand: "Expand learning steps",
    stepsCollapse: "Collapse learning steps",
    askAi: "Ask AI",
    aiQuickExplain: "Explain this step",
    aiQuickExample: "Give an example",
    aiQuickHelp: "Help me answer",
    aiContextHint: "Ask about the current step — I won't give away quiz answers directly.",
    submitAnswer: "Submit Answer",
    startSpeaking: "Start Speaking",
    stopSpeaking: "Stop",
    speechNotSupported:
      "Speech recognition is not supported in this browser. Type the phrase below instead.",
    speechTypeFallback: "Type the expected phrase",
    speechTypePlaceholder: "Type what you would say…",
    speechSubmitTyped: "Submit typed answer",
    speechSayPhrase: "Say this phrase",
    speechListening: "Listening… Speak clearly into your microphone",
    speechTapMic: "Tap the microphone to start speaking",
    speechYouSaid: "You said:",
    speechScore: (percent: number) => `Match score: ${percent}%`,
    speechPass: "Great pronunciation!",
    speechRetry: "Try again — match the expected sentence more closely.",
    listenAudio: "Listen to the audio",
    essayPlaceholder: "Write your answer...",
    answerToContinue: "Answer this step to continue.",
    answerSaveFailed: "Could not save your answer. Please try again.",
    answerSubToContinue: "Answer this question to continue.",
    submitEssayToContinue: "Write your answer and tap Submit Answer to continue.",
    completeSpeechToContinue:
      "Use the microphone or type your answer, then submit to continue.",
    advanceToNextPart: "Tap Next to continue to the next part of this question.",
    subQuestionNav: "Sub-questions",
    subQuestionPart: (current: number, total: number) =>
      `Part ${current} of ${total}`,
    readToContinue: "Read the material, then continue.",
    learningPath: "Learning path",
    sidebarProgress: (done: number, total: number) => `${done} of ${total} steps`,
    stepTypePretest: "Pretest",
    stepTypePosttest: "Posttest",
    stepTypeMaterial: "Material",
    stepTypeQuestion: "Question",
    pretestSummary: (n: number) => `Pretest (${n} questions)`,
    posttestSummary: (n: number) => `Posttest (${n} questions)`,
    materialCount: (n: number) => `${n} materials`,
    questionCount: (n: number) => `${n} questions`,
    pretestCount: (n: number) => `${n} pretest`,
    posttestCount: (n: number) => `${n} posttest`,
    materialsPhase: "Materials & Questions",
    posttestAfterContent: "Complete all materials and questions to unlock the posttest.",
    pretestTitle: "Pretest",
    pretestIntro:
      "Before you start the materials, rate how much you agree with each statement (1–5).",
    posttestTitle: "Posttest",
    posttestIntro:
      "You finished the materials! Rate the same statements again to reflect what you learned.",
    assessmentQuestionOf: (current: number, total: number) =>
      `Question ${current} of ${total}`,
    scaleLabel: (value: number) => `Rating: ${value}`,
    scaleMin: "1 — Strongly disagree",
    scaleMax: "5 — Strongly agree",
    startMaterials: "Start Materials",
    continueToPosttest: "Continue to Posttest",
    completePosttest: "Complete Posttest",
    answerAllAssessment: "Select a rating to continue.",
    assessmentRemaining: (count: number) =>
      count === 1
        ? "1 pretest/posttest question is still unanswered. Use Previous or the sidebar to complete it."
        : `${count} pretest/posttest questions are still unanswered. Use Previous or the sidebar to complete them.`,
  },
  login: {
    heroTitle: "Learn. Quiz. Level Up.",
    heroEarnPoints: "Earn points",
    heroAiFeedback: "AI feedback",
    title: "Sign In",
    subtitle: "Gamification learning platform",
    demoAdmin: "Admin: admin@gamifikasi.com / admin123",
    demoStudent: "Student: student@gamifikasi.com / student123",
  },
  meta: {
    title: "Next Gamifikasi",
    description: "Gamification learning platform with AI",
  },
  badges: {
    title: "Badges",
    subtitle: "Collect achievements as you master each language skill",
    earned: "Earned Badges",
    earnedCount: (earned: number, total: number) => `${earned} / ${total} earned`,
    viewAll: "View All Badges",
    viewAllBadges: "View All Badges",
    swipeHint: "Swipe to see more",
    noBadges: "Keep learning to earn your first badge!",
    badgesNew: (count: number) => `${count} new badge${count === 1 ? "" : "s"} unlocked!`,
    justUnlocked: "New Badge Unlocked!",
    nextUnlock: "Next up",
    skillMastery: "Skill Mastery",
    milestones: "Milestones",
    excellence: "Excellence",
    progress: (current: number, target: number) => `${current} / ${target}`,
    locked: "Locked",
    badgePreview: "Your Badges",
    allEarned: "All badges earned!",
    nextBadgeHint: (name: string) => `${name} next`,
    sectionEarned: "Earned",
    sectionLocked: "Locked",
    tier: {
      bronze: "Bronze",
      silver: "Silver",
      gold: "Gold",
      platinum: "Platinum",
      diamond: "Diamond",
    },
    names: {
      "first-step": "First Step",
      "quick-learner": "Quick Learner",
      "vocab-hunter": "Vocabulary Hunter",
      "reading-champion": "Reading Champion",
      "grammar-master": "Grammar Master",
      "speaking-star": "Speaking Star",
      "listening-expert": "Listening Expert",
      "perfect-score": "Perfect Score",
      "streak-master": "Streak Master",
      centurion: "Centurion",
      champion: "Champion",
      "eagle-eye": "Eagle Eye",
    },
    descriptions: {
      "first-step": "Complete your first learning group",
      "quick-learner": "Complete 3 learning groups",
      "vocab-hunter": "Answer 10 Reading questions correctly",
      "reading-champion": "Answer 25 Reading questions correctly",
      "grammar-master": "Answer 15 Writing questions correctly",
      "speaking-star": "Score 90%+ on 10 speech recognition exercises",
      "listening-expert": "Answer 15 Listening questions correctly",
      "perfect-score": "Complete a group with all questions answered correctly",
      "streak-master": "Complete 3 groups in a row",
      centurion: "Earn 500 points",
      champion: "Complete all groups in one level",
      "eagle-eye": "90%+ accuracy across 20+ questions",
    },
  },
  ranking: {
    title: "Leaderboard",
    subtitle: "See how you rank among all learners worldwide",
    yourRank: "Your Rank",
    yourPoints: "Your Points",
    yourTier: "Your Tier",
    nextTier: (needed: number) => `${needed} pts to next tier`,
    points: (pts: number) => `${pts} pts`,
    pts: "pts",
    podium: "Podium",
    allParticipants: "All Participants",
    you: "You",
    maxTier: "Max tier reached!",
    groupsCompletedStat: (completed: number) =>
      `${completed} group${completed === 1 ? "" : "s"} completed`,
    viewLeaderboard: "View Leaderboard",
    rankPreview: "Your standing",
    rankOf: (rank: number, total: number) => `#${rank} of ${total}`,
    rankSummary: (rank: number, tierLabel: string) => `#${rank} · ${tierLabel}`,
    noParticipants: "No participants yet. Start learning to earn points!",
    tiers: {
      bronze: "Bronze",
      silver: "Silver",
      gold: "Gold",
      platinum: "Platinum",
      diamond: "Diamond",
      master: "Master",
    },
    tierDescriptions: {
      bronze: "0 — 99 pts",
      silver: "100 — 299 pts",
      gold: "300 — 599 pts",
      platinum: "600 — 999 pts",
      diamond: "1,000 — 1,499 pts",
      master: "1,500+ pts",
    },
  },
  profile: {
    title: "My Profile",
    subtitle: "View and update your personal information.",
    myProfile: "My Profile",
    photoSection: "Profile Photo",
    photoHint: "Upload a photo (JPEG, PNG, WebP, or GIF, max 2 MB).",
    changePhoto: "Change photo",
    uploading: "Uploading...",
    uploadFailed: "Failed to upload photo.",
    passwordSection: "Change Password",
    passwordHint: "Leave blank to keep your current password.",
    saveSuccess: "Profile saved successfully.",
    saveFailed: "Failed to save profile.",
  },
  points: {
    earned: (pts: number) => `+${pts} points earned!`,
    earnedHint: "Keep learning to climb the leaderboard.",
    onTimeBonus: (pts: number) => `+${pts} on-time bonus!`,
    materialComplete: (pts: number) => `+${pts} for completing material`,
    correctAnswer: (pts: number) => `+${pts} for correct answer`,
    discussion: (pts: number) => `+${pts} for active discussion`,
    groupComplete: (pts: number) => `+${pts} for finishing the group`,
    dueAt: "Due date",
    dueAtHint: "Students earn a bonus if they finish before this date.",
    dueAtUnset: "No due date",
  },
  proficiency: {
    title: "Proficiency Level",
    subtitle: "Your language skill level based on answer quality.",
    score: (score: number) => `${score} proficiency pts`,
    scoreLabel: "Proficiency score",
    progressToNext: (needed: number, nextLevel: string) =>
      `${needed} pts to ${nextLevel}`,
    maxLevel: "Maximum level reached!",
    levels: {
      beginner: "Beginner",
      elementary: "Elementary",
      intermediate: "Intermediate",
      upperIntermediate: "Upper Intermediate",
      advanced: "Advanced",
    },
    levelDescriptions: {
      beginner: "0 — 29 pts · Just getting started",
      elementary: "30 — 99 pts · Building foundations",
      intermediate: "100 — 249 pts · Growing confidence",
      upperIntermediate: "250 — 499 pts · Strong communicator",
      advanced: "500+ pts · Advanced mastery",
    },
    levelUpTitle: (level: string) => `Level up! ${level}`,
    levelUpDescription: (description: string) => description,
    separateFromRanking:
      "Separate from ranking tiers — based on answer quality, not activity points.",
  },
  progress: {
    sectionTitle: "Learning Progress",
    sectionSubtitle: "Track materials, level, and skill mastery",
    materialTitle: "Material Completion",
    materialHint: (completed: number, total: number) =>
      `${completed} of ${total} steps completed`,
    levelTitle: "Level Progress",
    skillsTitle: "Skills",
    skillDone: (attempted: number, total: number, accuracy: number) =>
      `${attempted}/${total} done · ${accuracy}% accuracy`,
    skillAttempted: (attempted: number, total: number) =>
      `${attempted}/${total} done`,
    skillNotStarted: "Not started yet",
  },
  rewards: {
    pageTitle: "Rewards & Achievements",
    pageSubtitle:
      "Earn certificates, bonus points, and unlock premium content as you learn.",
    previewTitle: "Rewards",
    previewEarned: (earned: number, total: number) =>
      `${earned} of ${total} achievements`,
    previewCertificates: (count: number) =>
      `${count} certificate${count === 1 ? "" : "s"} earned`,
    previewEmpty: "Complete groups to earn your first reward",
    viewAll: "View all rewards",
    tabAchievements: "Achievements",
    tabCertificates: "Certificates",
    tabUnlocks: "Premium Unlocks",
    sectionEarned: "Earned",
    sectionLocked: "In Progress",
    progress: (current: number, target: number) => `${current} / ${target}`,
    unlockedTitle: "Achievement Unlocked!",
    unlockedSubtitle: "Your learning milestone comes with new rewards.",
    bonusPoints: (points: number) => `+${points} bonus points`,
    premiumUnlocked: "Premium Content Unlocked",
    premiumUnlockedHint: (levelLabel: string) =>
      `Premium groups in ${levelLabel} are now available.`,
    viewCertificate: "View certificate",
    certificateDetailTitle: "Digital Certificate",
    backToRewards: "Back to rewards",
    certificatePresentedTo: "This certificate is proudly presented to",
    certificateBody: (levelLabel: string) =>
      `For successfully completing all learning groups in the ${levelLabel} track and demonstrating commitment to English mastery.`,
    issuedOn: (date: string) => `Issued on ${date}`,
    downloadCertificate: "Download / Print",
    noCertificates: "No certificates yet",
    noCertificatesHint: "Complete an entire level to earn your first certificate.",
    unlocked: "Unlocked",
    locked: "Locked",
    premiumGroupsUnlocked: (count: number) =>
      `${count} premium group${count === 1 ? "" : "s"} available`,
    premiumGroupsLocked: (count: number) =>
      `${count} premium group${count === 1 ? "" : "s"} locked`,
    requirementHint: (achievementTitle: string) =>
      `Reach "${achievementTitle}" to unlock`,
    premiumBadge: "Premium",
    premiumLocked: "Premium locked",
    premiumLockedHint: (requirement: string) =>
      `${requirement} — view requirements`,
    viewRequirements: "View requirements",
    nextRewardHint: (hint: string) => hint,
  },
  challenges: {
    pageTitle: "Challenges & Missions",
    pageSubtitle:
      "Complete daily and weekly targets to earn extra bonus points.",
    previewTitle: "Challenges",
    viewAll: "View all",
    completedCount: (done: number, total: number) =>
      `${done}/${total} completed this period`,
    nextHint: (title: string, percent: number) =>
      `${title} · ${percent}% progress`,
    allComplete: "All challenges for this period are complete!",
    reward: "Reward",
    statusDone: "Completed",
    statusActive: "In progress",
    endingSoon: "Ending soon",
    timeLeftDays: (days: number) => `${days} day${days === 1 ? "" : "s"} left`,
    timeLeftHours: (hours: number) => `${hours} hour${hours === 1 ? "" : "s"} left`,
    timeLeftMinutes: (minutes: number) =>
      `${minutes} minute${minutes === 1 ? "" : "s"} left`,
    empty: "No active challenges yet.",
    completed: (title: string) => `Challenge complete: ${title}`,
    completedHint: (pts: number) => `+${pts} bonus points added!`,
    startDaily: "Start Daily Challenge",
    dailyTitle: "Daily Challenge",
    dailySubtitle:
      "5 random questions from the question bank — refreshed every day.",
    dailyProgress: "Today's progress",
    dailyQuestionsDone: "questions completed",
    dailyQuestionOf: (current: number, total: number) =>
      `Question ${current} of ${total}`,
    dailyAlreadyAnswered: "You already answered this question today.",
    dailyNoQuestions:
      "No questions available yet. Ask an admin to publish learning groups.",
    dailyUnsupportedFormat: "This question format is not supported in daily challenge.",
    dailyDoneTitle: "Daily Challenge complete!",
    dailyDoneHint: (pts: number) =>
      `You completed 5 questions today. +${pts} bonus points added.`,
    dailyUnavailable: "Daily challenge is not available right now.",
    backToList: "Back to Challenges",
  },
  api: {
    feedbackUnavailable: "AI feedback is unavailable right now.",
  },
} as const;

export type GroupStatus = "notStarted" | "inProgress" | "completed";

export function getLevelLabel(name: string): string {
  return labels.levels[name as keyof typeof labels.levels] ?? name;
}

export function getStatusLabel(status: GroupStatus): string {
  return labels.status[status];
}
