export const labels = {
  auth: {
    signIn: "Sign In",
    signUp: "Sign Up",
    signingIn: "Signing in...",
    signingUp: "Creating account...",
    signOut: "Sign Out",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    invalidCredentials: "Invalid email or password.",
    continueWithGoogle: "Continue with Google",
    signInWithEmailPassword: "Sign in with email and password",
    signUpWithEmailPassword: "Sign up with email and password",
    orContinueWithEmail: "or continue with email",
    googleSignInFailed: "Google sign-in failed. Please try again.",
    emailPlaceholder: "name@email.com",
    haveAccount: "Already have an account?",
  },
  nav: {
    brand: "Gamifikasi",
    home: "Home",
    learn: "Learning",
    chat: "AI Chat",
    dashboard: "Dashboard",
    levels: "Levels",
    users: "Users",
    analytics: "Analytics",
    gamification: "Gamification",
    announcements: "Announcements",
    chatMonitor: "Chat Monitor",
    settings: "Settings",
    database: "Database",
    breadcrumb: {
      dashboard: "Dashboard",
      users: "Users",
      ranking: "Ranking",
      newUser: "New User",
      editUser: "Edit User",
      levels: "Levels",
      groups: "Groups",
      newGroup: "New Group",
      content: "Content",
      addContent: "Add Content",
      newMaterial: "New Material",
      newQuestion: "New Question",
      editItem: "Edit Item",
      level: "Level",
      group: "Group",
      home: "Home",
      learning: "Learning",
      aiChat: "AI Chat",
      speaking: "Speaking",
      reading: "Reading",
      listening: "Listening",
      multipleChoice: "Multiple Choice",
      essay: "Essay",
      speechRecognition: "Speech Recognition",
      profile: "Profile",
      testimonials: "Testimonials",
      apiTokens: "API Tokens",
      apiTokensAudit: "Audit",
      apiTokensAllActivity: "All activity",
      apiTokenAudit: "Token audit",
      assistantKnowledge: "Assistant Knowledge",
      analytics: "Analytics",
      gamification: "Gamification",
      announcements: "Announcements",
      chatMonitor: "Chat Monitor",
      settings: "Settings",
      database: "Database",
    },
    adminPanel: "Admin Panel",
    learning: "Learning Hub",
    menu: "Menu",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    openMenu: "Open menu",
    openSteps: "Steps",
    closeSteps: "Close steps",
    defaultStudent: "Student",
    ranking: "Ranking",
    badges: "Badges",
    challenges: "Challenges",
    rewards: "Rewards",
    testimonials: "Testimonials",
    apiTokens: "API Tokens",
    assistantKnowledge: "Assistant Knowledge",
    points: (pts: number) => `${pts} pts`,
  },
  theme: {
    toggle: "Theme",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  levels: {
    BASIC: "Basic",
    INTERMEDIATE: "Intermediate",
    HARD: "Advanced",
  },
  status: {
    notStarted: "Not Started",
    inProgress: "In Progress",
    completed: "Completed",
    published: "Published",
    draft: "Draft",
  },
  common: {
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    title: "Title",
    content: "Content",
    correct: "Correct",
    search: "Search",
    paginationNav: "Pagination",
    paginationPrevious: "Previous",
    paginationNext: "Next",
    paginationShowing: (from: number, to: number, total: number) =>
      `Showing ${from}–${to} of ${total}`,
    paginationPage: (page: number, totalPages: number) =>
      `Page ${page} of ${totalPages}`,
  },
  admin: {
    dashboardTitle: "Admin Dashboard",
    dashboardDescription:
      "Overview of students, content, and learning levels.",
    totalStudents: "Total Students",
    totalGroups: "Total Groups",
    totalQuestions: "Total Questions",
    manageLevels: "Manage Levels",
    groupsPublished: (total: number, published: number) =>
      `${total} groups · ${published} published`,
    learningLevels: "Learning Levels",
    manageContent: "Manage Content",
    levelPrefix: (name: string) => `Level: ${name}`,
    addNewGroup: "Add New Group",
    groupTitle: "Group Title",
    premiumContent: "Premium content",
    premiumContentHint: "Requires proficiency achievement to unlock for students.",
    groupTitlePlaceholder: "Introduction to Variables",
    autoOrder: (order: number) => `Auto order: ${order}`,
    saveTitle: "Save title",
    unsavedTitleHint: "Title changed — tap the check button to save.",
    editorViewMode: "Editor view mode",
    viewModeEditor: "Editor",
    viewModeSplit: "Split",
    viewModePreview: "Preview",
    dragToResize: "Drag to resize",
    contentItemMeta: (id: number, order: number) => `ID: ${id} · Order: ${order}`,
    saveFailed: "Could not save. Try again.",
    saveSuccess: "Saved successfully.",
    saving: "Saving…",
    noGroupsDescription:
      "Create your first group to start adding materials and questions.",
    createGroupCta: "Create new group",
    noGroups: "No groups yet. Add a new group.",
    materialsCount: (materials: number, questions: number) =>
      `${materials} materials · ${questions} questions`,
    groupContents: "Contents",
    showContents: "Show contents",
    hideContents: "Hide contents",
    groupContentsEmpty: "No content items in this group yet.",
    publish: "Publish",
    unpublish: "Unpublish",
    tabMaterials: "Materials",
    tabQuestions: "Questions",
    addContent: "Add Content",
    chooseContentType: "Choose what you want to create",
    createMaterial: "Create Material",
    createQuestion: "Create Question",
    noMaterialsYet: "No materials yet. Create your first material.",
    noQuestionsYet: "No questions yet. Create your first question.",
    contentSummary: (materials: number, questions: number) =>
      `${materials} materials · ${questions} questions`,
    saveMaterial: "Save Material",
    addMaterial: "Add Material",
    newMaterial: "New Material",
    materialPlaceholder: "Material content...",
    addQuestion: "Add Question",
    questionPlaceholder: "Question text",
    optionA: "Option A",
    optionB: "Option B",
    optionC: "Option C",
    optionD: "Option D",
    correctAnswer: "Correct Answer",
    explanationOptional: "Explanation (optional)",
    addItem: "Add Item",
    pickType: "What do you want to add?",
    typeMaterial: "Material",
    typeMaterialDesc: "Rich text lesson with images and links",
    typeQuestion: "Question",
    typeQuestionDesc:
      "One question item with multiple sub-questions (skills, formats, weights). Total weight must equal 100%.",
    pickSkill: "Choose skill type",
    skillSpeaking: "Speaking",
    skillReading: "Reading",
    skillWriting: "Writing",
    skillListening: "Listening",
    pickFormat: "Choose answer format",
    formatMcq: "Multiple Choice (A–D)",
    formatYesNo: "Yes / No",
    formatEssay: "Essay",
    formatSpeech: "Speech Recognition",
    addSubQuestion: "Add sub-question",
    removeSubQuestion: "Remove",
    subQuestionOf: (current: number, total: number) =>
      `Sub-question ${current} of ${total}`,
    weightPercent: "Weight (%)",
    totalWeight: (total: number) => `Total weight: ${total}%`,
    weightNeedMore: (need: number) => `Need ${need}% more to reach 100%`,
    weightOver: (over: number) => `${over}% over 100% — adjust weights`,
    weightValid: "Weights total 100%",
    moveUp: "Move up",
    moveDown: "Move down",
    subQuestionsCount: (count: number) => `${count} sub-questions`,
    expectedSpeech: "Expected sentence (for speech match)",
    uploadAudio: "Upload audio file",
    uploadImage: "Upload image",
    materialPreview: "Preview",
    questionTextLabel: "Question",
    answerOptions: "Answer options",
    correctBadge: "Correct",
    explanationLabel: "Explanation",
    materialPreviewEmpty: "Start writing to see the preview here.",
    materialAttachments: "Attachments",
    materialAttachmentsHint:
      "Upload PDF, PowerPoint, Word, Excel, images, or other allowed files. Maximum 10 files.",
    uploadAttachment: "Upload file",
    removeAttachment: "Remove",
    attachmentUploading: "Uploading…",
    attachmentUploadError: "Could not upload file. Check the type and size, then try again.",
    attachmentPartialFailed: (count: number, names: string) =>
      `${count} file(s) failed (${names}). Successful uploads were kept.`,
    attachmentPreviewPdf: "PDF preview",
    attachmentPreviewPptx: "Presentation preview",
    attachmentDownload: "Download file",
    attachmentUnsupported: "Preview is not available for this file type.",
    attachmentMaxCount: "Maximum 10 files per material.",
    attachmentPptxPrev: "Previous slide",
    attachmentPptxNext: "Next slide",
    attachmentPptxSlide: (current: number, total: number) =>
      `Slide ${current} of ${total}`,
    attachmentPptxLoadError:
      "Could not render this presentation. Download the file to open it in PowerPoint.",
    editorLabel: "Editor",
    showDetails: "Show details",
    hideDetails: "Hide details",
    showPreview: "Show preview",
    hidePreview: "Hide preview",
    essayRubric: "Essay rubric (optional)",
    contentItems: (count: number) => `${count} items in sequence`,
    noItemsYet: "No content yet. Add your first material or question.",
    chatMonitorTitle: "Chat Monitor",
    chatMonitorDescription:
      "Review student AI chat history across all days. Filter by student or date range.",
    chatMonitorFilterStudent: "Student",
    chatMonitorFilterDate: "Date range",
    chatMonitorDateAll: "All time",
    chatMonitorDateToday: "Today (WIB)",
    chatMonitorDateYesterday: "Yesterday (WIB)",
    chatMonitorDateLast7Days: "Last 7 days",
    chatMonitorAllStudents: "All students",
    chatMonitorEmpty: "No chat messages match your filters.",
    chatMonitorRoleUser: "Student",
    chatMonitorRoleAssistant: "Assistant",
    chatMonitorGeneralChat: "General",
    usersTitle: "User Management",
    usersDescription: "Manage student and admin accounts for login.",
    testimonialsTitle: "Student Testimonials",
    testimonialsDescription:
      "Reviews submitted after students complete a learning group.",
    testimonialStudent: "Student",
    testimonialLevel: "Level",
    testimonialGroup: "Group",
    testimonialScore: "Score",
    testimonialRating: "Rating",
    testimonialText: "Testimonial",
    testimonialDate: "Submitted",
    testimonialAiFeedback: "AI feedback",
    testimonialEmpty: "No testimonials submitted yet.",
    testimonialViewDetails: "View details",
    testimonialSearchPlaceholder: "Search by student name…",
    rankingTitle: "Student Rankings",
    rankingDescription:
      "View all student leaderboard positions, tiers, and points.",
    rankedStudents: "Ranked Students",
    topScore: "Top Score",
    addUser: "Add User",
    editUser: "Edit User",
    noUsersYet: "No users yet. Add your first user.",
    searchUsers: "Search by name, email, phone, school, or NIS/NIM...",
    filterAll: "All",
    filterStudents: "Students",
    filterAdmins: "Admins",
    accountSection: "Account",
    profileSection: "Personal Data",
    fullName: "Full Name",
    fullNamePlaceholder: "e.g. Budi Santoso",
    phone: "Phone Number",
    phonePlaceholder: "e.g. 081234567890",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    genderMale: "Male",
    genderFemale: "Female",
    genderUnset: "Not specified",
    institution: "School / Institution",
    institutionPlaceholder: "e.g. SMA Negeri 1 Jakarta",
    studentId: "NIS / NIM",
    studentIdPlaceholder: "e.g. NIS-2024001",
    userRole: "Role",
    userActive: "Active (can login)",
    userInactive: "Inactive",
    password: "Password",
    passwordPlaceholder: "Min. 6 characters",
    passwordOptional: "New password (leave blank to keep current)",
    points: "Points",
    deleteUserTitle: "Delete user?",
    deleteUserDescription: (name: string) =>
      `This will permanently delete ${name} and all their progress, answers, and chat history.`,
    requiredFieldHint: "Fields marked with * are required.",
    userCreated: "User created successfully.",
    userUpdated: "User updated successfully.",
    itemMaterial: "Material",
    itemQuestion: "Question",
    stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
    stepsNav: "Steps",
    groupComplete: "Group complete!",
    finishGroup: "Finish Group",
    finishGroupHint: "Submit your feedback to unlock the next group.",
    assessmentsSection: "Pretest & Posttest",
    assessmentsHint:
      "Students rate each statement 1–5 (1 = strongly disagree, 5 = strongly agree). Pretest appears before materials; posttest after all content is done.",
    pretest: "Pretest",
    posttest: "Posttest",
    addAssessmentQuestion: "Add question",
    assessmentQuestionPlaceholder: "e.g. I understand the topic of this group.",
    noPretestQuestions: "No pretest questions yet.",
    noPosttestQuestions: "No posttest questions yet.",
    assessmentScaleHint: "Students answer with a 1–5 slider only.",
    deleteAssessmentQuestion: "Delete question",
    apiTokensTitle: "API Tokens",
    apiTokensDescription:
      "Manage Bearer tokens for external apps calling the Ollama gateway.",
    apiTokensTabTokens: "Tokens",
    apiTokensTabConsole: "API Console",
    apiTokensTabDocs: "Documentation",
    apiTokensCreate: "Create Token",
    apiTokensName: "Token name",
    apiTokensNamePlaceholder: "e.g. Production backend",
    apiTokensPrefix: "Prefix",
    apiTokensLastUsed: "Last used",
    apiTokensExpires: "Expires",
    apiTokensNever: "Never",
    apiTokensRevoke: "Revoke",
    apiTokensActivate: "Activate",
    apiTokensRotate: "Rotate",
    apiTokensDelete: "Delete",
    apiTokensEmpty: "No API tokens yet. Create one for your external app.",
    apiTokensCreatedTitle: "Token created",
    apiTokensCreatedHint:
      "Copy this token now. It will not be shown again.",
    apiTokensRotatedTitle: "Token rotated",
    apiTokensRotatedHint:
      "Copy the new token now. The previous token is invalid.",
    apiTokensCopy: "Copy token",
    apiTokensCopied: "Copied!",
    apiTokensClose: "Close",
    apiTokensUseInConsole: "Use in console",
    apiTokensScopes: "Scopes",
    apiTokensScopeChat: "Chat",
    apiTokensScopeGenerate: "Generate",
    apiTokensScopeModels: "Models",
    apiTokensAllowedOrigins: "Allowed origins (optional)",
    apiTokensAllowedOriginsHint:
      "Comma-separated URLs for browser apps. Leave empty to use the global CORS allowlist.",
    apiTokensAllowedOriginsPlaceholder: "https://app.example.com, http://localhost:3000",
    apiTokensExpiry: "Expiry (optional)",
    apiTokensExpiryHint: "Leave empty for no expiry.",
    apiTokensSecurityWarning:
      "Treat API tokens like passwords. Secrets are encrypted in the database and can be revealed by admins. Restrict admin access and rotate tokens if leaked.",
    apiTokensShowToken: "Show token",
    apiTokensRevealedTitle: "Stored token",
    apiTokensRevealedHint:
      "This token is stored encrypted. Copy it now if you need it elsewhere.",
    apiTokensRevealUnavailable:
      "No stored secret for this token. Rotate to generate a new recoverable token.",
    apiTokensAuditTitle: "Recent requests",
    apiTokensAuditEmpty: "No requests logged yet.",
    apiTokensAuditEndpoint: "Endpoint",
    apiTokensAuditStatus: "Status",
    apiTokensAuditIp: "IP",
    apiTokensAuditTime: "Time",
    apiTokensTimezoneNote: "Times shown in WIB (Western Indonesian Time).",
    apiTokensCorsTitle: "Global CORS allowlist",
    apiTokensCorsHint:
      "Origins allowed for browser clients when a token has no per-token origins.",
    apiTokensCorsSave: "Save CORS allowlist",
    apiTokensCorsSaved: "CORS allowlist saved.",
    apiTokensAudit: "View audit",
    apiTokensAllActivity: "All activity",
    apiTokensAuditPageTitle: "Token audit",
    apiTokensAllActivityTitle: "API activity",
    apiTokensAllActivityDescription:
      "Review requests across all tokens. Filter by token to focus on one client.",
    apiTokensAuditDescription:
      "Usage chart, daily quota, and request history for this token.",
    apiTokensDailyQuota: "Daily quota",
    apiTokensDailyQuotaHint:
      "Maximum API requests per calendar day (WIB). Leave empty for unlimited.",
    apiTokensDailyQuotaPlaceholder: "e.g. 500",
    apiTokensDailyQuotaUnlimited: "Unlimited",
    apiTokensDailyQuotaSave: "Save daily quota",
    apiTokensUsageToday: (used: number, limit: number | null) =>
      limit != null ? `${used} / ${limit} requests today` : `${used} requests today (unlimited)`,
    apiTokensUsageChartTitle: "Request volume",
    apiTokensUsageChart7Days: "7 days",
    apiTokensUsageChart30Days: "30 days",
    apiTokensUsageChartSuccess: "Success (2xx)",
    apiTokensUsageChartClientError: "Client errors (4xx)",
    apiTokensUsageChartRateLimited: "Rate limited (429)",
    apiTokensAuditTokenColumn: "Token",
    apiTokensAuditFilterAll: "All tokens",
    apiTokensAuditFilterLabel: "Filter by token",
    apiTokensBackToTokens: "Back to tokens",
    apiTokensQuotaRemaining: (remaining: number) => `${remaining} remaining today`,
    assistantKnowledgeTitle: "Assistant Knowledge",
    assistantKnowledgeDescription:
      "Manage Brader Saintek Unipda FAQ entries for instant answers about identity and campus facts.",
    assistantKnowledgeHint:
      "Published entries with matching keywords return instantly without calling Ollama. Higher priority wins ties.",
    assistantKnowledgeAdd: "Add Entry",
    assistantKnowledgeCreate: "Create Entry",
    assistantKnowledgeCreateTitle: "New knowledge entry",
    assistantKnowledgeEditTitle: "Edit knowledge entry",
    assistantKnowledgeSave: "Save Entry",
    assistantKnowledgeEmpty: "No knowledge entries yet.",
    assistantKnowledgeEmptyHint:
      "Add FAQ entries for Brader Saintek Unipda (identity, Unipda facts, developer team).",
    assistantKnowledgeSlug: "Slug",
    assistantKnowledgeSlugPlaceholder: "about-unipda",
    assistantKnowledgePriority: "Priority",
    assistantKnowledgePriorityValue: (value: number) => `Priority ${value}`,
    assistantKnowledgeKeywords: "Keywords",
    assistantKnowledgeKeywordsPlaceholder: "unipda, universitas pgri delta, apa itu unipda",
    assistantKnowledgeKeywordsHint:
      "Comma-separated phrases used to match user questions. Multi-word phrases work best.",
    assistantKnowledgeQuestionEn: "Sample question (English)",
    assistantKnowledgeQuestionId: "Sample question (Indonesian)",
    assistantKnowledgeAnswerEn: "Answer (English)",
    assistantKnowledgeAnswerId: "Answer (Indonesian)",
    assistantKnowledgePublished: "Published",
    assistantKnowledgePublish: "Publish",
    assistantKnowledgeUnpublish: "Unpublish",
    assistantKnowledgeUpdated: "Updated",
    assistantKnowledgeDeleteConfirm:
      "Delete this knowledge entry? Brader will no longer use it for instant answers.",
    assistantKnowledgeSearchPlaceholder: "Search slug, questions, or answers",
    assistantKnowledgeSearchEmpty: "No matching entries",
    assistantKnowledgeSearchEmptyHint:
      "Try a different search term or clear the filter to see all entries.",
    apiConsoleTitle: "API Console",
    apiConsoleDescription:
      "Test External API endpoints with your Bearer token.",
    apiConsoleOverview:
      "The External API is a secure HTTP gateway that proxies requests to the local Ollama AI server. Use it from backend apps (Python, Node, Laravel) or browser apps (with CORS) to run chat completions, text generation, and list models — without exposing Ollama directly to the internet.",
    apiConsolePurposeLabel: "What it does",
    apiConsoleAuthLabel: "Authentication",
    apiConsolePayloadLabel: "Request payload",
    apiConsoleResponseLabel: "Response",
    apiConsoleExamplePayloadLabel: "Example JSON",
    apiConsoleCurlLabel: "curl command",
    apiConsoleCurlHint:
      "Uses your Bearer token and request body when set. Paste into a terminal to run the same request outside the browser.",
    apiConsoleScopeRequired: (scope: string) => `Required token scope: ${scope}`,
    apiConsoleScopePublic: "No Bearer token required (public discovery).",
    apiConsoleEndpoints: {
      discovery: {
        purpose:
          "Returns the live API catalog: available routes, authentication rules, rate limits, and example payloads.",
        auth: "Public — send GET with no Authorization header.",
        payload:
          "No request body. Optional: none.",
        response:
          "JSON with name, version, baseUrl, authentication, rateLimit, endpoints[], and error codes.",
      },
      models: {
        purpose:
          "Lists AI models available on the Ollama server (proxies Ollama GET /api/tags). Use this to check which model names you can pass in chat or generate requests.",
        auth: "Authorization: Bearer <token> with the models scope.",
        payload: "No request body.",
        response:
          'JSON from Ollama, e.g. { "models": [{ "name": "llama3.2", ... }] }.',
      },
      chat: {
        purpose:
          "Multi-turn chat completion. Send a conversation (messages array) and receive an assistant reply from Ollama. Best for conversational AI in your app.",
        auth: "Authorization: Bearer <token> with the chat scope.",
        payload:
          "JSON body fields:\n• messages (required) — array of 1–32 objects: { \"role\": \"system\" | \"user\" | \"assistant\", \"content\": string }. Max 8192 characters per message.\n• stream (optional) — boolean, default false. Set true for streaming NDJSON chunks.\n• model (optional) — string, overrides the server default Ollama model.",
        response:
          "Non-stream: Ollama chat JSON (message, done, eval counts, …). Stream: application/x-ndjson — one JSON object per line as tokens arrive.",
      },
      generate: {
        purpose:
          "Single-shot text generation from one prompt (proxies Ollama POST /api/generate). Use for summaries, feedback, or one-off completions.",
        auth: "Authorization: Bearer <token> with the generate scope.",
        payload:
          "JSON body fields:\n• prompt (required) — string, 1–8192 characters.\n• stream (optional) — boolean, default false.\n• model (optional) — string, overrides default Ollama model.",
        response:
          'Non-stream: { "response": "...", "done": true, ... }. Stream: NDJSON lines with partial response text.',
      },
    },
    apiConsoleMethod: "Method",
    apiConsoleEndpoint: "Endpoint",
    apiConsoleBearerToken: "Bearer token",
    apiConsoleBearerHint: "Stored in sessionStorage for this tab only.",
    apiConsoleClearToken: "Clear token",
    apiConsoleRequestBody: "Request body (JSON)",
    apiConsoleFormatJson: "Format JSON",
    apiConsoleValidateJson: "Validate JSON",
    apiConsoleSend: "Send request",
    apiConsoleSending: "Sending…",
    apiConsoleResponse: "Response",
    apiConsoleResponseFull: "Full response (raw JSON)",
    apiConsoleResponseHint:
      "Ollama returns metadata (durations, token counts) plus the assistant text. The summary above shows the readable part only.",
    apiConsoleResponseError: "Error",
    apiConsoleResponseAssistant: "Assistant reply",
    apiConsoleResponseGenerated: "Generated text",
    apiConsoleResponseModels: "Available models",
    apiConsoleResponseStream: "Stream output",
    apiConsoleStatus: "Status",
    apiConsoleDuration: "Duration",
    apiConsoleInvalidJson: "Invalid JSON in request body.",
    apiConsoleStreamNote: "Streaming response — chunks append below.",
    apiDocsTitle: "API Documentation",
    apiDocsDescription:
      "Live discovery document and integration examples.",
    apiDocsOverview:
      "The External API (base path /api/v1) is an Ollama proxy gateway. Create a Bearer token in the Tokens tab, then call endpoints from your backend or browser app.",
    apiDocsEndpointReference: "Endpoint reference",
    apiDocsDiscovery: "Discovery (GET /api/v1)",
    apiDocsCopyJson: "Copy JSON",
    apiDocsStep1: "Create an API token in the Tokens tab.",
    apiDocsStep2: "Copy the Bearer token once — it cannot be retrieved later.",
    apiDocsStep3: "Call endpoints with Authorization: Bearer <token>.",
    apiDocsStep4:
      "Handle 401 (invalid token), 403 (scope/CORS), 429 (rate limit), and 502 (Ollama error).",
    apiDocsCorsNote:
      "Browser apps from other domains need an allowed origin (global or per-token CORS).",
    apiDocsExamples: "Code examples",
    apiDocsExampleCurl: "curl",
    apiDocsExampleFetch: "JavaScript fetch",
    apiDocsExamplePython: "Python requests",
    analyticsTitle: "Learning Analytics",
    analyticsDescription:
      "Track student activity, completion rates, question difficulty, and drop-off points.",
    analyticsActivity: "Student activity",
    analyticsActive7: "Active (7 days)",
    analyticsActive30: "Active (30 days)",
    analyticsInactive: "Inactive (30+ days)",
    analyticsLevelCompletion: "Completion by level",
    analyticsGroupCompletion: "Completion by group",
    analyticsCompletionRate: "Completion rate",
    analyticsQuestionDifficulty: "Hardest questions",
    analyticsAttempts: "Attempts",
    analyticsSuccessRate: "Success rate",
    analyticsSkillHeatmap: "Skill performance",
    analyticsDropOff: "Drop-off hotspots",
    analyticsStuckStudents: "Stuck students",
    gamificationTitle: "Gamification",
    gamificationDescription:
      "Manage challenges, achievements, certificates, and point values.",
    gamificationTabChallenges: "Challenges",
    gamificationTabAchievements: "Achievements",
    gamificationTabCertificates: "Certificates",
    gamificationTabPoints: "Point values",
    gamificationCreateChallenge: "Create challenge",
    gamificationCreateAchievement: "Create achievement",
    gamificationPointReward: "Point reward",
    gamificationActive: "Active",
    gamificationInactive: "Inactive",
    gamificationSavePoints: "Save point values",
    previewTitle: "Student preview",
    previewDescription:
      "See how materials and questions appear to students in this group.",
    previewBanner:
      "This is a read-only preview. Progress and answers are not saved.",
    previewAsStudent: "Preview as student",
    cloneGroup: "Clone group",
    exportGroup: "Export JSON",
    importGroup: "Import JSON",
    versionEmpty: "No saved versions for this item yet.",
    versionNumber: (n: number) => `Version ${n}`,
    versionRestore: "Restore version",
    aiCopilot: "AI content copilot",
    aiCopilotHint:
      "Generate draft MCQ or material JSON from a topic. Review before publishing.",
    aiCopilotTopic: "Topic or learning objective",
    aiCopilotGenerateMcq: "Generate MCQ draft",
    aiCopilotGenerateMaterial: "Generate material draft",
    aiCopilotGenerating: "Generating…",
    aiCopilotError: "Could not generate content. Try again.",
    atRiskTitle: "At-risk students",
    atRiskDescription:
      "Students who may need a nudge based on inactivity, stuck progress, or low accuracy.",
    atRiskEmpty: "No at-risk students right now.",
    atRiskReasonStuck: "Stuck",
    atRiskReasonInactive: "Inactive",
    atRiskReasonOverdue: "Overdue",
    atRiskReasonLowAccuracy: "Low accuracy",
    announcementsTitle: "Announcements",
    announcementsDescription:
      "Create banners and notices shown to students and admins on the dashboard.",
    announcementsCreate: "Create announcement",
    announcementsEdit: "Edit announcement",
    announcementsEmpty:
      "No announcements yet. Create one to show a banner on the dashboard.",
    announcementsTitleField: "Title",
    announcementsMessage: "Message",
    announcementsLinkUrl: "Link URL (optional)",
    announcementsLinkLabel: "Link label (optional)",
    announcementsStartsAt: "Starts at",
    announcementsEndsAt: "Ends at (optional)",
    announcementsTargetRole: "Audience",
    announcementsTargetAll: "Everyone",
    announcementsTargetStudent: "Students only",
    announcementsTargetAdmin: "Admins only",
    announcementsActive: "Active",
    announcementsInactive: "Inactive",
    announcementsSave: "Save announcement",
    announcementsDelete: "Delete",
    announcementsDeleteConfirm:
      "Delete this announcement? This cannot be undone.",
    announcementsSaved: "Announcement saved.",
    announcementsDeleted: "Announcement deleted.",
    settingsTitle: "Settings",
    settingsDescription:
      "Platform configuration, external API access, and environment summary.",
    settingsCorsTitle: "Global CORS allowlist",
    settingsCorsDescription:
      "Comma-separated origins allowed to call the External API from a browser. Manage tokens on the API Tokens page.",
    settingsCorsSave: "Save CORS allowlist",
    settingsCorsSaved: "CORS allowlist saved.",
    settingsPlatformTitle: "Platform",
    settingsPlatformDescription:
      "Quick links to related admin tools and read-only deployment info.",
    settingsOllamaModel: "Ollama model",
    settingsOllamaBaseUrl: "Ollama base URL",
    settingsAuthUrl: "Public URL",
    settingsManageApiTokens: "Manage API tokens",
    settingsManageGamification: "Point values & gamification",
    settingsManageDatabase: "Database backup",
    databaseTitle: "Database Backup",
    databaseDescription:
      "Download a full SQL backup or restore the database from a .sql file.",
    databaseBackupTitle: "Download backup",
    databaseBackupDescription:
      "Exports all tables, routines, and triggers as a single .sql file.",
    databaseDownloadBackup: "Download SQL backup",
    databaseBackupRunning: "Creating backup…",
    databaseBackupError: "Could not create backup. Try again.",
    databaseImportTitle: "Import backup",
    databaseImportDescription:
      "Replace current database contents with a .sql backup file (max 100 MB).",
    databaseImportFile: "SQL file",
    databaseImportSubmit: "Import SQL file",
    databaseImportRunning: "Importing…",
    databaseImportSuccess: "Database imported successfully.",
    databaseImportError: "Could not import backup. Check the file and try again.",
    databaseImportFileRequired: "Choose a .sql file to import.",
    databaseImportInvalidType: "Only .sql files are supported.",
    databaseImportFileTooLarge: "File is too large. Maximum size is 100 MB.",
    databaseImportConfirmRequired:
      "Confirm that you understand import will overwrite current data.",
    databaseImportConfirmLabel:
      "I understand this will overwrite all current database data.",
    databaseImportWarningTitle: "Destructive operation",
    databaseImportWarning:
      "Import replaces every table in the database. Download a fresh backup before importing.",
    userProgress: {
      tabProfile: "Profile",
      tabProgress: "Progress",
      tabFeedback: "Feedback",
      feedbackListTitle: "AI Feedback Library",
      feedbackListSubtitle:
        "Browse AI feedback for every answer and group completion in one place.",
      feedbackFilterAll: "All",
      feedbackFilterWithAi: "With AI feedback",
      feedbackFilterCorrect: "Correct",
      feedbackFilterIncorrect: "Incorrect",
      feedbackFilterCompletion: "Group completion",
      feedbackEmpty: "No answers or feedback recorded yet.",
      feedbackEmptyFilter: "No items match this filter.",
      feedbackViewDetail: "View detail",
      feedbackCompletionKind: "Group completion",
      feedbackAnswerKind: "Question answer",
      feedbackTotal: (count: number) => `${count} items`,
      feedbackWithAiCount: (count: number) => `${count} with AI feedback`,
      feedbackQuestion: "Question",
      feedbackPreview: "Feedback preview",
      feedbackNoPreview: "No AI feedback generated for this answer yet.",
      feedbackFilterGroup: "Showing feedback for the selected group only.",
      groupsCompleted: "Groups Completed",
      materialOverall: "Material Overall",
      proficiency: "Proficiency",
      lastActivity: "Last Activity",
      noActivity: "No activity yet",
      skillsTitle: "Skills Overview",
      levelProgressTitle: "Progress by Level",
      groupsInLevel: (completed: number, total: number) =>
        `${completed}/${total} groups`,
      phasePretest: "Pretest",
      phaseContent: "Content",
      phasePosttest: "Posttest",
      phaseFinished: "Done",
      pretestCount: (answered: number, total: number) =>
        `Pretest ${answered}/${total}`,
      posttestCount: (answered: number, total: number) =>
        `Posttest ${answered}/${total}`,
      contentSteps: (completed: number, total: number) =>
        `Content ${completed}/${total}`,
      contentAnswerStats: (correct: number, incorrect: number) =>
        `${correct} correct · ${incorrect} incorrect`,
      groupScore: (score: number) => `Score: ${score}%`,
      testimonialRating: (rating: number) => `Rating: ${rating}/5`,
      lastActive: (date: string) => `Last active: ${date}`,
      emptyNotStarted: "Student has not started any group yet.",
      emptyNotStudent: "Progress tracking is for student accounts.",
      listProgress: (completed: number, total: number) =>
        `${completed}/${total} groups`,
      listInProgress: (level: string) => `${level} · In progress`,
      listNotStarted: "Not started",
      listCompleted: "All groups completed",
      assessmentAnswer: (value: number) => `${value}/5`,
      noAnswer: "—",
      expandDetails: "Show details",
      collapseDetails: "Hide details",
      assessmentQuestions: "Assessment answers",
      contentSummary: "Content answers",
      noAssessmentQuestions: "No assessment questions in this group.",
      historyTitle: "Activity History",
      historyEmpty: "No activity recorded yet.",
      historyGroupStarted: (group: string) => `Started group: ${group}`,
      historyGroupCompleted: (group: string, score: number | null) =>
        score != null
          ? `Completed group: ${group} (${score}%)`
          : `Completed group: ${group}`,
      historyContentAnswer: (item: string) => `Answered: ${item}`,
      historyAssessmentAnswer: (phase: string, question: string) =>
        `${phase}: ${question}`,
      historyTestimonial: (group: string) => `Submitted testimonial for ${group}`,
      historyViewFeedback: "View AI feedback",
      feedbackTitle: "AI Feedback",
      completionFeedbackTitle: "Group completion feedback",
      answerFeedbackTitle: "Answer feedback",
      studentAnswer: "Student answer",
      noFeedback: "No feedback yet.",
      answerCorrect: "Correct",
      answerIncorrect: "Incorrect",
      answerScore: (score: number) => `Score: ${score}%`,
    },
  },
  student: {
    welcome: (name: string) => `Welcome, ${name}!`,
    homePoints: "Points",
    homeRank: "Rank",
    homeProgress: "Progress",
    homeViewLeaderboard: "View Leaderboard",
    homePointsToTier: (pts: number, tier: string) => `${pts} pts to ${tier}`,
    homeGroupsProgress: (completed: number, total: number) =>
      `${completed} of ${total} groups completed`,
    homeContinueLearning: "Continue Learning",
    homeResume: "Resume",
    homeLearningLevels: "Learning Levels",
    homeReview: "Review",
    reviewAgain: "Review Again",
    finishGroup: "Finish Group",
    finishGroupFailed: "Could not prepare completion. Try again.",
    completionLoadFailed: "Could not load your score. Try again.",
    retryLoad: "Try again",
    progressUpdateFailed: "Could not save progress. Try again.",
    levelGroupsStat: (completed: number, total: number) => `${completed}/${total}`,
    levelGroupsLabel: "groups",
    noPublishedGroupsDescription:
      "Check back later or ask your instructor to publish groups for this level.",
    chooseLevel: "Choose a level to start or continue learning.",
    groupsCompleted: (completed: number, total: number) =>
      `${completed} groups completed of ${total} groups`,
    startLearning: "Start Learning",
    continueLearning: "Continue Learning",
    materialsProgress: (percent: number) => `${percent}% complete`,
    stepsProgress: (percent: number) => `${percent}% complete`,
    start: "Start",
    continue: "Continue",
    finishGroupHint: "Submit your feedback to unlock the next group.",
    unlockPrevious:
      "Complete the previous group first.",
    noPublishedGroups: "No published groups for this level yet.",
    backToLevel: "Back to Level",
    backToMaterials: "Back to Materials",
    noMaterials: "No materials yet. Return to the group list.",
    materialsNav: "Materials",
    previous: "Previous",
    next: "Next",
    takeQuiz: "Take Quiz",
    quizTitle: (title: string) => `Quiz: ${title}`,
    noQuestions: "No questions for this group yet.",
    questionOf: (current: number, total: number) =>
      `Question ${current} of ${total}`,
    correctAnswer: "Correct!",
    wrongAnswer: "Incorrect",
    correctAnswerIs: "Correct answer:",
    explanation: "Explanation",
    nextQuestion: "Next Question",
    viewResults: "View Results",
    quizComplete: "Complete!",
    completionScore: "Your score",
    completionScoreLabel: (percent: number) => `${percent}%`,
    aiCompletionFeedback: "AI Feedback",
    aiCompletionLoading: "Generating your personalized feedback…",
    testimonialTitle: "Share your experience",
    testimonialSubtitle:
      "Your testimonial is required before you can leave this page.",
    testimonialRatingLabel: "Rating",
    testimonialRatingRequired: "Please select a rating from 1 to 5 stars.",
    testimonialPlaceholder:
      "Tell us what you learned and how this group helped you…",
    testimonialRequired: "Testimonial is required to finish this group.",
    testimonialMinLength: "Please write at least 20 characters.",
    testimonialAlreadySubmitted: "You have already submitted a testimonial.",
    submitTestimonial: "Submit testimonial",
    testimonialSubmitting: "Submitting…",
    testimonialThankYou: "Thank you for your feedback!",
    scoreSummary: (score: number, total: number) =>
      `${score} of ${total} correct`,
    pointsAdded: (points: number) => `+${points} points added`,
    feedbackUnavailable: "Feedback unavailable.",
    feedbackLoadError: "Failed to load AI feedback.",
    chatTitle: "AI Chat",
    chatSubtitle:
      "Learning assistant to help you understand course materials.",
    chatDailyResetHint:
      "Chat resets every day at 12:00 AM WIB. Only today's messages are shown here.",
    chatPlaceholder: "Type your question...",
    chatSend: "Send",
    chatSending: "Sending…",
    chatKeyboardHint: "Enter to send · Shift+Enter for new line",
    chatRespondedIn: (duration: string) => `Responded in ${duration}`,
    chatGeneratingElapsed: (duration: string) => `Generating answer… · ${duration}`,
    chatGenerating: "Generating answer…",
    chatError: "Sorry, something went wrong. Please try again later.",
    chatNetworkError:
      "Connection failed. The AI service may be starting up — wait a moment and try again.",
    chatTimeoutError:
      "The request took too long. Try a shorter question or try again in a moment.",
    aiAssistantTitle: "AI Assistant",
    aiAssistantOpen: "Open AI Assistant",
    aiAssistantClose: "Collapse AI Assistant",
    aiAssistantExpand: "Expand AI Assistant",
    stepsOpen: "Open learning steps",
    stepsExpand: "Expand learning steps",
    stepsCollapse: "Collapse learning steps",
    askAi: "Ask AI",
    aiQuickExplain: "Explain this step",
    aiQuickExample: "Give an example",
    aiQuickHelp: "Help me answer",
    aiContextHint: "Ask about the current step — I won't give away quiz answers directly.",
    submitAnswer: "Submit Answer",
    startSpeaking: "Start Speaking",
    stopSpeaking: "Stop",
    speechNotSupported:
      "Speech recognition is not supported in this browser. Type the phrase below instead.",
    speechTypeFallback: "Type the expected phrase",
    speechTypePlaceholder: "Type what you would say…",
    speechSubmitTyped: "Submit typed answer",
    speechSayPhrase: "Say this phrase",
    speechListening: "Listening… Speak clearly into your microphone",
    speechTapMic: "Tap the microphone to start speaking",
    speechYouSaid: "You said:",
    speechScore: (percent: number) => `Match score: ${percent}%`,
    speechPass: "Great pronunciation!",
    speechRetry: "Try again — match the expected sentence more closely.",
    listenAudio: "Listen to the audio",
    essayPlaceholder: "Write your answer...",
    answerToContinue: "Answer this step to continue.",
    answerSaveFailed: "Could not save your answer. Please try again.",
    answerSubToContinue: "Answer this question to continue.",
    submitEssayToContinue: "Write your answer and tap Submit Answer to continue.",
    completeSpeechToContinue:
      "Use the microphone or type your answer, then submit to continue.",
    advanceToNextPart: "Tap Next to continue to the next part of this question.",
    subQuestionNav: "Sub-questions",
    subQuestionPart: (current: number, total: number) =>
      `Part ${current} of ${total}`,
    readToContinue: "Read the material, then continue.",
    learningPath: "Learning path",
    sidebarProgress: (done: number, total: number) => `${done} of ${total} steps`,
    stepTypePretest: "Pretest",
    stepTypePosttest: "Posttest",
    stepTypeMaterial: "Material",
    viewAttachment: "Attached file",
    downloadAttachment: "Download attachment",
    stepTypeQuestion: "Question",
    pretestSummary: (n: number) => `Pretest (${n} questions)`,
    posttestSummary: (n: number) => `Posttest (${n} questions)`,
    materialCount: (n: number) => `${n} materials`,
    questionCount: (n: number) => `${n} questions`,
    pretestCount: (n: number) => `${n} pretest`,
    posttestCount: (n: number) => `${n} posttest`,
    materialsPhase: "Materials & Questions",
    posttestAfterContent: "Complete all materials and questions to unlock the posttest.",
    pretestTitle: "Pretest",
    pretestIntro:
      "Before you start the materials, rate how much you agree with each statement (1–5).",
    posttestTitle: "Posttest",
    posttestIntro:
      "You finished the materials! Rate the same statements again to reflect what you learned.",
    assessmentQuestionOf: (current: number, total: number) =>
      `Question ${current} of ${total}`,
    scaleLabel: (value: number) => `Rating: ${value}`,
    scaleMin: "1 — Strongly disagree",
    scaleMax: "5 — Strongly agree",
    startMaterials: "Start Materials",
    continueToPosttest: "Continue to Posttest",
    completePosttest: "Complete Posttest",
    answerAllAssessment: "Select a rating to continue.",
    assessmentRemaining: (count: number) =>
      count === 1
        ? "1 pretest/posttest question is still unanswered. Use Previous or the sidebar to complete it."
        : `${count} pretest/posttest questions are still unanswered. Use Previous or the sidebar to complete them.`,
  },
  login: {
    heroTitle: "Learn. Quiz. Level Up.",
    heroEarnPoints: "Earn points",
    heroAiFeedback: "AI feedback",
    title: "Sign In",
    subtitle: "Gamification learning platform",
    backToHome: "Back to home",
    haveAccount: "Already have an account?",
  },
  register: {
    title: "Create Account",
    subtitle: "Join the platform and start learning with AI-powered feedback.",
    accountSection: "Account",
    profileSection: "Personal Data",
    requiredHint: "Fields marked with * are required.",
    submit: "Create Account",
    emailTaken: "This email is already registered. Sign in or use another email.",
    passwordMismatch: "Passwords do not match.",
    invalidInput: "Please check your details and try again.",
  },
  landing: {
    meta: {
      title: "Gamifikasi — Learn. Quiz. Level Up.",
      description:
        "Gamified learning with AI feedback, leaderboards, badges, and daily challenges.",
    },
    nav: {
      features: "Features",
      howItWorks: "How it works",
      leaderboard: "Leaderboard",
      signIn: "Sign In",
    },
    hero: {
      badge: "Gamified learning platform",
      title: "Learn. Quiz. Level Up.",
      subtitle:
        "Progress through structured levels, get AI-powered feedback, and compete on leaderboards — all in one place.",
      getStarted: "Get Started",
      exploreFeatures: "Explore features",
    },
    features: {
      title: "Everything you need to stay motivated",
      subtitle: "Built for learners who want structure, feedback, and real progress.",
      items: {
        learning: {
          title: "Structured Learning",
          description:
            "Move through levels, groups, materials, and quizzes at your own pace with clear progress tracking.",
        },
        ai: {
          title: "AI Assistant",
          description:
            "Get contextual help while you learn and instant feedback on essays — powered by local AI.",
        },
        ranking: {
          title: "Leaderboards",
          description:
            "Climb the ranks, unlock tiers, and see how you compare with other learners.",
        },
        badges: {
          title: "Badges & Skills",
          description:
            "Earn achievements as you master speaking, reading, and listening skills.",
        },
        rewards: {
          title: "Rewards",
          description:
            "Collect points, unlock certificates, and celebrate milestones along the way.",
        },
        challenges: {
          title: "Daily Challenges",
          description:
            "Stay consistent with daily targets and streaks that keep you coming back.",
        },
      },
    },
    steps: {
      title: "How it works",
      subtitle: "Three simple steps from signup to mastery.",
      items: {
        choose: {
          title: "Choose your level",
          description:
            "Pick Basic, Intermediate, or Advanced and start with the right challenge.",
        },
        learn: {
          title: "Learn & quiz",
          description:
            "Study materials, answer questions, and get AI feedback when you need it.",
        },
        earn: {
          title: "Earn rank & rewards",
          description:
            "Gain points, badges, and leaderboard standing as you complete groups.",
        },
      },
    },
    stats: {
      label: "Designed for engaged learners",
      points: "Points & tiers",
      ai: "AI-powered feedback",
      skills: "Multi-skill practice",
    },
    leaderboard: {
      title: "Live Leaderboard",
      subtitle: "Compete with learners worldwide and climb from Bronze to Master",
      participants: (count: number) =>
        `${count} learner${count === 1 ? "" : "s"} competing`,
      topTen: "Top 10",
      joinCta: "Join the Leaderboard",
      emptyTitle: "Be the first on the podium",
      emptySubtitle:
        "Sign in, complete lessons, earn points, and claim the top spot.",
      tiersTitle: "Climb the tiers",
    },
    cta: {
      title: "Ready to level up?",
      subtitle: "Sign in and start your learning journey today.",
      button: "Sign In to Start",
    },
    footer: {
      tagline: "Gamification learning with AI",
      signIn: "Sign In",
      createdBy: "Created by IT Unipda Sidoarjo",
    },
    scrollToTop: "Scroll to top",
  },
  meta: {
    title: "Next Gamifikasi",
    description: "Gamification learning platform with AI",
  },
  badges: {
    title: "Badges",
    subtitle: "Collect achievements as you master each language skill",
    earned: "Earned Badges",
    earnedCount: (earned: number, total: number) => `${earned} / ${total} earned`,
    viewAll: "View All Badges",
    viewAllBadges: "View All Badges",
    swipeHint: "Swipe to see more",
    noBadges: "Keep learning to earn your first badge!",
    badgesNew: (count: number) => `${count} new badge${count === 1 ? "" : "s"} unlocked!`,
    justUnlocked: "New Badge Unlocked!",
    nextUnlock: "Next up",
    skillMastery: "Skill Mastery",
    milestones: "Milestones",
    excellence: "Excellence",
    progress: (current: number, target: number) => `${current} / ${target}`,
    locked: "Locked",
    badgePreview: "Your Badges",
    allEarned: "All badges earned!",
    nextBadgeHint: (name: string) => `${name} next`,
    sectionEarned: "Earned",
    sectionLocked: "Locked",
    tier: {
      bronze: "Bronze",
      silver: "Silver",
      gold: "Gold",
      platinum: "Platinum",
      diamond: "Diamond",
    },
    names: {
      "first-step": "First Step",
      "quick-learner": "Quick Learner",
      "vocab-hunter": "Vocabulary Hunter",
      "reading-champion": "Reading Champion",
      "grammar-master": "Grammar Master",
      "speaking-star": "Speaking Star",
      "listening-expert": "Listening Expert",
      "perfect-score": "Perfect Score",
      "streak-master": "Streak Master",
      centurion: "Centurion",
      champion: "Champion",
      "eagle-eye": "Eagle Eye",
    },
    descriptions: {
      "first-step": "Complete your first learning group",
      "quick-learner": "Complete 3 learning groups",
      "vocab-hunter": "Answer 10 Reading questions correctly",
      "reading-champion": "Answer 25 Reading questions correctly",
      "grammar-master": "Answer 15 Writing questions correctly",
      "speaking-star": "Score 90%+ on 10 speech recognition exercises",
      "listening-expert": "Answer 15 Listening questions correctly",
      "perfect-score": "Complete a group with all questions answered correctly",
      "streak-master": "Complete 3 groups in a row",
      centurion: "Earn 500 points",
      champion: "Complete all groups in one level",
      "eagle-eye": "90%+ accuracy across 20+ questions",
    },
  },
  ranking: {
    title: "Leaderboard",
    subtitle: "See how you rank among all learners worldwide",
    yourRank: "Your Rank",
    yourPoints: "Your Points",
    yourTier: "Your Tier",
    nextTier: (needed: number) => `${needed} pts to next tier`,
    points: (pts: number) => `${pts} pts`,
    pts: "pts",
    podium: "Podium",
    allParticipants: "All Participants",
    you: "You",
    maxTier: "Max tier reached!",
    groupsCompletedStat: (completed: number) =>
      `${completed} group${completed === 1 ? "" : "s"} completed`,
    viewLeaderboard: "View Leaderboard",
    rankPreview: "Your standing",
    rankOf: (rank: number, total: number) => `#${rank} of ${total}`,
    rankSummary: (rank: number, tierLabel: string) => `#${rank} · ${tierLabel}`,
    noParticipants: "No participants yet. Start learning to earn points!",
    tiers: {
      bronze: "Bronze",
      silver: "Silver",
      gold: "Gold",
      platinum: "Platinum",
      diamond: "Diamond",
      master: "Master",
    },
    tierDescriptions: {
      bronze: "0 — 99 pts",
      silver: "100 — 299 pts",
      gold: "300 — 599 pts",
      platinum: "600 — 999 pts",
      diamond: "1,000 — 1,499 pts",
      master: "1,500+ pts",
    },
  },
  profile: {
    title: "My Profile",
    subtitle: "View and update your personal information.",
    myProfile: "My Profile",
    photoSection: "Profile Photo",
    photoHint: "Upload a photo (JPEG, PNG, WebP, or GIF, max 2 MB).",
    changePhoto: "Change photo",
    uploading: "Uploading...",
    uploadFailed: "Failed to upload photo.",
    passwordSection: "Change Password",
    passwordHint: "Leave blank to keep your current password.",
    saveSuccess: "Profile saved successfully.",
    saveFailed: "Failed to save profile.",
  },
  points: {
    earned: (pts: number) => `+${pts} points earned!`,
    earnedHint: "Keep learning to climb the leaderboard.",
    onTimeBonus: (pts: number) => `+${pts} on-time bonus!`,
    materialComplete: (pts: number) => `+${pts} for completing material`,
    correctAnswer: (pts: number) => `+${pts} for correct answer`,
    discussion: (pts: number) => `+${pts} for active discussion`,
    groupComplete: (pts: number) => `+${pts} for finishing the group`,
    dueAt: "Due date",
    dueAtHint: "Students earn a bonus if they finish before this date.",
    dueAtUnset: "No due date",
  },
  proficiency: {
    title: "Proficiency Level",
    subtitle: "Your language skill level based on answer quality.",
    score: (score: number) => `${score} proficiency pts`,
    scoreLabel: "Proficiency score",
    progressToNext: (needed: number, nextLevel: string) =>
      `${needed} pts to ${nextLevel}`,
    maxLevel: "Maximum level reached!",
    levels: {
      beginner: "Beginner",
      elementary: "Elementary",
      intermediate: "Intermediate",
      upperIntermediate: "Upper Intermediate",
      advanced: "Advanced",
    },
    levelDescriptions: {
      beginner: "0 — 29 pts · Just getting started",
      elementary: "30 — 99 pts · Building foundations",
      intermediate: "100 — 249 pts · Growing confidence",
      upperIntermediate: "250 — 499 pts · Strong communicator",
      advanced: "500+ pts · Advanced mastery",
    },
    levelUpTitle: (level: string) => `Level up! ${level}`,
    levelUpDescription: (description: string) => description,
    separateFromRanking:
      "Separate from ranking tiers — based on answer quality, not activity points.",
  },
  progress: {
    sectionTitle: "Learning Progress",
    sectionSubtitle: "Track materials, level, and skill mastery",
    materialTitle: "Material Completion",
    materialHint: (completed: number, total: number) =>
      `${completed} of ${total} steps completed`,
    levelTitle: "Level Progress",
    skillsTitle: "Skills",
    skillDone: (attempted: number, total: number, accuracy: number) =>
      `${attempted}/${total} done · ${accuracy}% accuracy`,
    skillAttempted: (attempted: number, total: number) =>
      `${attempted}/${total} done`,
    skillNotStarted: "Not started yet",
  },
  rewards: {
    pageTitle: "Rewards & Achievements",
    pageSubtitle:
      "Earn certificates, bonus points, and unlock premium content as you learn.",
    previewTitle: "Rewards",
    previewEarned: (earned: number, total: number) =>
      `${earned} of ${total} achievements`,
    previewCertificates: (count: number) =>
      `${count} certificate${count === 1 ? "" : "s"} earned`,
    previewEmpty: "Complete groups to earn your first reward",
    viewAll: "View all rewards",
    tabAchievements: "Achievements",
    tabCertificates: "Certificates",
    tabUnlocks: "Premium Unlocks",
    sectionEarned: "Earned",
    sectionLocked: "In Progress",
    progress: (current: number, target: number) => `${current} / ${target}`,
    unlockedTitle: "Achievement Unlocked!",
    unlockedSubtitle: "Your learning milestone comes with new rewards.",
    bonusPoints: (points: number) => `+${points} bonus points`,
    premiumUnlocked: "Premium Content Unlocked",
    premiumUnlockedHint: (levelLabel: string) =>
      `Premium groups in ${levelLabel} are now available.`,
    viewCertificate: "View certificate",
    certificateDetailTitle: "Digital Certificate",
    backToRewards: "Back to rewards",
    certificatePresentedTo: "This certificate is proudly presented to",
    certificateBody: (levelLabel: string) =>
      `For successfully completing all learning groups in the ${levelLabel} track and demonstrating commitment to English mastery.`,
    issuedOn: (date: string) => `Issued on ${date}`,
    downloadCertificate: "Download / Print",
    noCertificates: "No certificates yet",
    noCertificatesHint: "Complete an entire level to earn your first certificate.",
    unlocked: "Unlocked",
    locked: "Locked",
    premiumGroupsUnlocked: (count: number) =>
      `${count} premium group${count === 1 ? "" : "s"} available`,
    premiumGroupsLocked: (count: number) =>
      `${count} premium group${count === 1 ? "" : "s"} locked`,
    requirementHint: (achievementTitle: string) =>
      `Reach "${achievementTitle}" to unlock`,
    premiumBadge: "Premium",
    premiumLocked: "Premium locked",
    premiumLockedHint: (requirement: string) =>
      `${requirement} — view requirements`,
    viewRequirements: "View requirements",
    nextRewardHint: (hint: string) => hint,
  },
  challenges: {
    pageTitle: "Challenges & Missions",
    pageSubtitle:
      "Complete daily and weekly targets to earn extra bonus points.",
    previewTitle: "Challenges",
    viewAll: "View all",
    completedCount: (done: number, total: number) =>
      `${done}/${total} completed this period`,
    nextHint: (title: string, percent: number) =>
      `${title} · ${percent}% progress`,
    allComplete: "All challenges for this period are complete!",
    reward: "Reward",
    statusDone: "Completed",
    statusActive: "In progress",
    endingSoon: "Ending soon",
    timeLeftDays: (days: number) => `${days} day${days === 1 ? "" : "s"} left`,
    timeLeftHours: (hours: number) => `${hours} hour${hours === 1 ? "" : "s"} left`,
    timeLeftMinutes: (minutes: number) =>
      `${minutes} minute${minutes === 1 ? "" : "s"} left`,
    empty: "No active challenges yet.",
    completed: (title: string) => `Challenge complete: ${title}`,
    completedHint: (pts: number) => `+${pts} bonus points added!`,
    startDaily: "Start Daily Challenge",
    dailyTitle: "Daily Challenge",
    dailySubtitle:
      "5 random questions from the question bank — refreshed every day.",
    dailyProgress: "Today's progress",
    dailyQuestionsDone: "questions completed",
    dailyQuestionOf: (current: number, total: number) =>
      `Question ${current} of ${total}`,
    dailyAlreadyAnswered: "You already answered this question today.",
    dailyNoQuestions:
      "No questions available yet. Ask an admin to publish learning groups.",
    dailyUnsupportedFormat: "This question format is not supported in daily challenge.",
    dailyDoneTitle: "Daily Challenge complete!",
    dailyDoneHint: (pts: number) =>
      `You completed 5 questions today. +${pts} bonus points added.`,
    dailyUnavailable: "Daily challenge is not available right now.",
    backToList: "Back to Challenges",
  },
  api: {
    feedbackUnavailable: "AI feedback is unavailable right now.",
  },
  errors: {
    unauthorized: "Unauthorized",
    forbidden: "Forbidden",
    notFound: "Not found",
    serverError: "Something went wrong. Please try again.",
    tooManyRequests: "Too many requests. Please try again later.",
    apiScopeDenied: "This token does not have permission for this endpoint.",
    corsOriginDenied: "Origin not allowed by CORS policy.",
    dailyQuotaExceeded: "Daily API quota exceeded for this token. Try again after midnight WIB.",
    ollamaUnavailable: "AI service is temporarily unavailable. Please try again.",
  },
} as const;

export type GroupStatus = "notStarted" | "inProgress" | "completed";

export function getLevelLabel(name: string): string {
  return labels.levels[name as keyof typeof labels.levels] ?? name;
}

export function getStatusLabel(status: GroupStatus): string {
  return labels.status[status];
}
