import { LevelName } from "@prisma/client";

export interface TopicCatalogEntry {
  title: string;
  level: LevelName;
  sections: string[];
  vocab: string[];
  questionStems: string[];
}

function topic(
  title: string,
  level: LevelName,
  sections: string[],
  vocab: string[],
  questionStems: string[]
): TopicCatalogEntry {
  const paddedSections =
    sections.length >= 10
      ? sections.slice(0, 10)
      : [
          ...sections,
          ...Array.from(
            { length: 10 - sections.length },
            (_, i) => `${title} — Review ${i + 1}`
          ),
        ];

  return { title, level, sections: paddedSections, vocab, questionStems };
}

const BASIC_TOPICS: TopicCatalogEntry[] = [
  topic(
    "Greetings & Introductions",
    LevelName.BASIC,
    [
      "Greetings in English",
      "Introducing Yourself",
      "Polite Expressions",
      "Formal vs Informal Greetings",
      "Meeting New People",
      "Asking Names and Origins",
      "Small Talk Basics",
      "Saying Goodbye",
      "Cultural Greetings",
      "Greetings Review",
    ],
    ["Hello", "Hi", "Good morning", "Nice to meet you", "Please", "Thank you", "Excuse me"],
    [
      "Which greeting is appropriate in the afternoon?",
      "How do you respond to 'Nice to meet you'?",
      "Say a polite greeting into the microphone.",
      "Write a short self-introduction.",
      "Is 'Hi' formal or informal?",
    ]
  ),
  topic(
    "Numbers & Colors",
    LevelName.BASIC,
    [
      "Numbers 1 to 20",
      "Colors Around Us",
      "Counting Objects",
      "Number Spelling",
      "Primary Colors",
      "Describing with Color",
      "Ordinal Numbers",
      "Color Mixing",
      "Numbers in Daily Life",
      "Numbers & Colors Review",
    ],
    ["One", "Two", "Red", "Blue", "Yellow", "Green", "Eleven", "Twenty", "Orange", "Purple"],
    [
      "What number comes after fourteen?",
      "What color is the sky on a clear day?",
      "Say the number 'seven' clearly.",
      "Describe your favorite color in 3 sentences.",
      "Is twelve spelled 'twelve'?",
    ]
  ),
  topic(
    "Daily Life",
    LevelName.BASIC,
    [
      "Daily Routines",
      "Food and Drinks",
      "Telling Time",
      "Morning Activities",
      "Evening Activities",
      "Healthy Habits",
      "Meal Times",
      "Time Expressions",
      "Weekend Routines",
      "Daily Life Review",
    ],
    ["Wake up", "Breakfast", "O'clock", "Half past", "Rice", "Water", "Homework", "Go to bed"],
    [
      "What do you do first in the morning?",
      "Which drink is the healthiest?",
      "How do you say 2:30 in English?",
      "Write about your morning routine.",
      "Do you brush your teeth after breakfast?",
    ]
  ),
  topic(
    "Family & Friends",
    LevelName.BASIC,
    [
      "Family Members",
      "Describing Family",
      "Friends and Classmates",
      "Possessive Adjectives",
      "Family Activities",
      "Talking About Age",
      "Relationships",
      "Family Traditions",
      "Inviting Friends",
      "Family & Friends Review",
    ],
    ["Mother", "Father", "Sister", "Brother", "Friend", "My", "Your", "Their", "Cousin", "Family"],
    [
      "Who is your mother's sister?",
      "Which possessive means 'belonging to us'?",
      "Say 'This is my family' into the microphone.",
      "Write about your best friend.",
      "Is 'cousin' a family member?",
    ]
  ),
  topic(
    "School & Classroom",
    LevelName.BASIC,
    [
      "Classroom Objects",
      "School Subjects",
      "School Routines",
      "Asking the Teacher",
      "Classroom Rules",
      "School Supplies",
      "Timetable Vocabulary",
      "School Places",
      "Study Habits",
      "School Review",
    ],
    ["Book", "Pen", "Teacher", "Student", "Math", "Science", "Homework", "Library", "Desk", "Class"],
    [
      "Where do you borrow books at school?",
      "Which subject studies numbers and shapes?",
      "Say 'I go to school every day'.",
      "Write about your favorite subject.",
      "Do students raise their hand before speaking?",
    ]
  ),
  topic(
    "Hobbies & Sports",
    LevelName.BASIC,
    [
      "Common Hobbies",
      "Sports Vocabulary",
      "Playing vs Doing",
      "Free Time Activities",
      "Indoor Hobbies",
      "Outdoor Sports",
      "Inviting to Play",
      "Equipment Vocabulary",
      "Team vs Individual Sports",
      "Hobbies Review",
    ],
    ["Football", "Reading", "Swimming", "Music", "Play", "Do", "Basketball", "Drawing", "Run", "Sing"],
    [
      "Do we say 'play football' or 'do football'?",
      "Which hobby uses a book?",
      "Say 'I like playing badminton'.",
      "Write about your hobby.",
      "Is swimming an outdoor sport?",
    ]
  ),
  topic(
    "Weather & Seasons",
    LevelName.BASIC,
    [
      "Weather Words",
      "Four Seasons",
      "Hot and Cold",
      "Rain and Sun",
      "Weather Questions",
      "Seasonal Activities",
      "Clothes for Weather",
      "Forecast Vocabulary",
      "Weather in Indonesia",
      "Weather Review",
    ],
    ["Sunny", "Rainy", "Cloudy", "Hot", "Cold", "Spring", "Summer", "Autumn", "Winter", "Windy"],
    [
      "What weather word describes rain?",
      "Which season comes after winter?",
      "Say 'It is sunny today'.",
      "Write about your favorite season.",
      "Is it usually hot in summer?",
    ]
  ),
  topic(
    "Body & Health",
    LevelName.BASIC,
    [
      "Body Parts",
      "Feeling Sick",
      "Healthy Food",
      "Exercise",
      "Doctor Visit",
      "Hygiene Habits",
      "Describing Pain",
      "Staying Healthy",
      "First Aid Basics",
      "Health Review",
    ],
    ["Head", "Hand", "Stomach", "Doctor", "Medicine", "Healthy", "Tired", "Sick", "Teeth", "Heart"],
    [
      "Which body part do you use to see?",
      "Who do you visit when you are sick?",
      "Say 'I have a headache'.",
      "Write 3 tips for staying healthy.",
      "Should you wash your hands before eating?",
    ]
  ),
  topic(
    "Food & Restaurant",
    LevelName.BASIC,
    [
      "Common Foods",
      "Ordering Food",
      "Restaurant Phrases",
      "Fruits and Vegetables",
      "Drinks Menu",
      "Tastes and Flavors",
      "Cooking Verbs",
      "Meals of the Day",
      "Polite Requests",
      "Food Review",
    ],
    ["Rice", "Chicken", "Menu", "Order", "Delicious", "Spicy", "Sweet", "Water", "Bill", "Waiter"],
    [
      "What do you say to order food politely?",
      "Which word means 'very tasty'?",
      "Say 'Can I have some water, please'.",
      "Write about your favorite meal.",
      "Is 'bill' what you pay at a restaurant?",
    ]
  ),
  topic(
    "Transportation",
    LevelName.BASIC,
    [
      "Types of Transport",
      "Going to Places",
      "Bus and Train",
      "Directions Basics",
      "Tickets and Fares",
      "Travel Safety",
      "Airport Words",
      "City Transport",
      "Asking for Directions",
      "Transport Review",
    ],
    ["Bus", "Car", "Train", "Airport", "Ticket", "Station", "Left", "Right", "Straight", "Taxi"],
    [
      "Where do planes take off?",
      "Which transport runs on rails?",
      "Say 'I take the bus to school'.",
      "Write how you go to school.",
      "Does 'straight' mean turn left?",
    ]
  ),
  topic(
    "Shopping & Money",
    LevelName.BASIC,
    [
      "Shops and Markets",
      "Prices and Money",
      "Buying and Selling",
      "Clothes Shopping",
      "Bargaining Phrases",
      "Payment Methods",
      "Receipts and Change",
      "Sizes and Colors",
      "Online Shopping",
      "Shopping Review",
    ],
    ["Price", "Cheap", "Expensive", "Buy", "Sell", "Money", "Size", "Small", "Large", "Discount"],
    [
      "What is the opposite of expensive?",
      "Where do you check the price?",
      "Say 'How much is this shirt?'",
      "Write about something you want to buy.",
      "Do you get change when you pay more than the price?",
    ]
  ),
  topic(
    "Animals & Nature",
    LevelName.BASIC,
    [
      "Farm Animals",
      "Wild Animals",
      "Pets at Home",
      "Animal Sounds",
      "Nature Places",
      "Trees and Plants",
      "Ocean Animals",
      "Protecting Nature",
      "Zoo Visit",
      "Animals Review",
    ],
    ["Dog", "Cat", "Bird", "Fish", "Elephant", "Forest", "River", "Tree", "Lion", "Farm"],
    [
      "Which animal says 'meow'?",
      "Where do wild animals usually live?",
      "Say 'I have a pet dog'.",
      "Write about your favorite animal.",
      "Is a whale a fish?",
    ]
  ),
  topic(
    "Home & Furniture",
    LevelName.BASIC,
    [
      "Rooms in a House",
      "Furniture Items",
      "Household Chores",
      "Prepositions at Home",
      "Kitchen Items",
      "Bedroom Vocabulary",
      "Living Room",
      "Cleaning Up",
      "Describing Your Home",
      "Home Review",
    ],
    ["Kitchen", "Bedroom", "Sofa", "Table", "Chair", "Bed", "Clean", "Cook", "Bathroom", "Garden"],
    [
      "Where do you usually cook food?",
      "Which furniture do you sleep on?",
      "Say 'My home has three bedrooms'.",
      "Describe your bedroom.",
      "Is a sofa found in the living room?",
    ]
  ),
  topic(
    "Jobs & Occupations",
    LevelName.BASIC,
    [
      "Common Jobs",
      "Workplaces",
      "What Do They Do?",
      "Dream Jobs",
      "Tools of the Trade",
      "Uniforms",
      "Helping Professions",
      "Office Jobs",
      "Job Interview Basics",
      "Jobs Review",
    ],
    ["Doctor", "Teacher", "Engineer", "Nurse", "Chef", "Police", "Office", "Hospital", "School", "Work"],
    [
      "Who helps sick people?",
      "Where does a teacher work?",
      "Say 'I want to be a doctor'.",
      "Write about your dream job.",
      "Does a chef work in a kitchen?",
    ]
  ),
  topic(
    "Holidays & Celebrations",
    LevelName.BASIC,
    [
      "National Holidays",
      "Birthday Party",
      "Festival Vocabulary",
      "Gifts and Cards",
      "Holiday Food",
      "Family Gatherings",
      "New Year",
      "Religious Celebrations",
      "Holiday Traditions",
      "Holidays Review",
    ],
    ["Birthday", "Gift", "Party", "Celebrate", "Holiday", "Fireworks", "Cake", "Family", "Tradition", "Festival"],
    [
      "What do people often eat on birthdays?",
      "Which word means a special day off?",
      "Say 'Happy birthday to you'.",
      "Write about your favorite holiday.",
      "Do people give gifts on holidays?",
    ]
  ),
];

const INTERMEDIATE_TOPICS: TopicCatalogEntry[] = [
  topic(
    "Talking About the Past",
    LevelName.INTERMEDIATE,
    [
      "Simple Past Tense",
      "Past Continuous Tense",
      "Time Expressions for the Past",
      "Regular Verbs",
      "Irregular Verbs",
      "Past Questions",
      "Past Negatives",
      "Used to",
      "Past Storytelling",
      "Past Tense Review",
    ],
    ["Yesterday", "Went", "Was", "Were", "Last week", "Ago", "Finished", "Started", "Did", "Had"],
    [
      "What is the past tense of 'go'?",
      "Which sentence uses past continuous?",
      "Say 'I was reading a book'.",
      "Write 3 sentences about yesterday.",
      "Is 'walked' the past of 'walk'?",
    ]
  ),
  topic(
    "Future Plans & Intentions",
    LevelName.INTERMEDIATE,
    [
      "Talking About the Future with Will",
      "Going To for Future Plans",
      "Present Continuous for Arrangements",
      "Future Time Expressions",
      "Will vs Going To",
      "Making Promises",
      "Predictions",
      "Future Questions",
      "Planning a Trip",
      "Future Review",
    ],
    ["Will", "Going to", "Tomorrow", "Next week", "Plan", "Promise", "Predict", "Arrange", "Future", "Soon"],
    [
      "Which sentence describes a planned intention?",
      "Is 'won't' short for 'will not'?",
      "Say 'I will call you tomorrow'.",
      "Write about your plans for next year.",
      "Can present continuous show future arrangements?",
    ]
  ),
  topic(
    "Describing People & Places",
    LevelName.INTERMEDIATE,
    [
      "Descriptive Adjectives",
      "Relative Clauses",
      "Prepositions of Place",
      "Describing Appearance",
      "Describing Personality",
      "Comparing Places",
      "There is / There are",
      "City vs Countryside",
      "Travel Descriptions",
      "Descriptions Review",
    ],
    ["Tall", "Friendly", "Beautiful", "Who", "Which", "Where", "Between", "Next to", "Bustling", "Peaceful"],
    [
      "Which shows correct adjective order?",
      "Which relative pronoun is for places?",
      "Say 'The book is on the table'.",
      "Describe your favorite place with a relative clause.",
      "Is 'bustling' the same as peaceful?",
    ]
  ),
  topic(
    "Present Perfect Tense",
    LevelName.INTERMEDIATE,
    [
      "Have and Has",
      "Present Perfect Form",
      "Ever and Never",
      "For and Since",
      "Just, Already, Yet",
      "Life Experiences",
      "Unfinished Time",
      "Present Perfect vs Past Simple",
      "Been vs Gone",
      "Present Perfect Review",
    ],
    ["Have", "Has", "Ever", "Never", "Since", "For", "Already", "Yet", "Experienced", "Recently"],
    [
      "Complete: 'I ____ visited Bali.'",
      "Which time expression pairs with present perfect?",
      "Say 'I have finished my homework'.",
      "Write about places you have visited.",
      "Is 'since 2020' used with present perfect?",
    ]
  ),
  topic(
    "Modal Verbs",
    LevelName.INTERMEDIATE,
    [
      "Can and Could",
      "Must and Have To",
      "Should and Ought To",
      "May and Might",
      "Permission and Ability",
      "Advice with Modals",
      "Obligation vs Suggestion",
      "Modal Questions",
      "Polite Requests",
      "Modals Review",
    ],
    ["Can", "Could", "Must", "Should", "May", "Might", "Have to", "Ability", "Permission", "Advice"],
    [
      "Which modal shows ability?",
      "What is the difference between must and should?",
      "Say 'You should study every day'.",
      "Write advice for a new student.",
      "Can 'may' ask for permission?",
    ]
  ),
  topic(
    "Comparatives & Superlatives",
    LevelName.INTERMEDIATE,
    [
      "Comparative Adjectives",
      "Superlative Adjectives",
      "As...As Comparisons",
      "Irregular Comparisons",
      "Comparing People",
      "Comparing Places",
      "Much vs Many",
      "Less and More",
      "Opinion Comparisons",
      "Comparatives Review",
    ],
    ["Bigger", "Better", "Best", "More", "Less", "Than", "As", "Worst", "Faster", "Most interesting"],
    [
      "What is the comparative of 'good'?",
      "Complete: 'She is taller ____ me.'",
      "Say 'This book is more interesting than that one'.",
      "Compare two cities you know.",
      "Is 'best' a superlative?",
    ]
  ),
  topic(
    "Phrasal Verbs",
    LevelName.INTERMEDIATE,
    [
      "Common Phrasal Verbs",
      "Separable Phrasal Verbs",
      "Inseparable Phrasal Verbs",
      "Phrasal Verbs at Work",
      "Phrasal Verbs at School",
      "Look, Get, Take Verbs",
      "Turn On and Off",
      "Give Up and Carry On",
      "Context Clues",
      "Phrasal Verbs Review",
    ],
    ["Give up", "Look after", "Turn on", "Take off", "Get up", "Find out", "Carry on", "Put on", "Wake up", "Run out"],
    [
      "What does 'give up' mean?",
      "Which phrasal verb means start a device?",
      "Say 'Please turn off the lights'.",
      "Write 3 sentences using phrasal verbs.",
      "Is 'look after' separable?",
    ]
  ),
  topic(
    "Travel & Tourism",
    LevelName.INTERMEDIATE,
    [
      "At the Airport",
      "Hotel Check-in",
      "Asking for Recommendations",
      "Booking Tickets",
      "Travel Problems",
      "Sightseeing Vocabulary",
      "Souvenirs and Shopping",
      "Public Transport Abroad",
      "Travel Safety Tips",
      "Travel Review",
    ],
    ["Passport", "Luggage", "Reservation", "Guidebook", "Souvenir", "Boarding pass", "Customs", "Delay", "Platform", "Check in"],
    [
      "What document do you need to travel abroad?",
      "Where do you collect your bags after a flight?",
      "Say 'I would like to check in, please'.",
      "Write about a place you want to visit.",
      "Is a boarding pass used at the gate?",
    ]
  ),
  topic(
    "Technology & Media",
    LevelName.INTERMEDIATE,
    [
      "Devices and Gadgets",
      "Internet Vocabulary",
      "Social Media",
      "Online Safety",
      "Streaming and Apps",
      "Email Etiquette",
      "Tech Problems",
      "Digital Habits",
      "News Media",
      "Technology Review",
    ],
    ["Smartphone", "Download", "Password", "Website", "App", "Wi-Fi", "Screen", "Upload", "Online", "Message"],
    [
      "What protects your online account?",
      "Which verb means get a file from the internet?",
      "Say 'I use my phone to study English'.",
      "Write about how you use technology.",
      "Should you share your password?",
    ]
  ),
  topic(
    "Environment & Society",
    LevelName.INTERMEDIATE,
    [
      "Environmental Problems",
      "Recycling Vocabulary",
      "Climate Change Basics",
      "Community Issues",
      "Volunteering",
      "Sustainable Living",
      "Pollution Types",
      "Protecting Wildlife",
      "Green Habits",
      "Environment Review",
    ],
    ["Pollution", "Recycle", "Climate", "Waste", "Energy", "Plastic", "Community", "Volunteer", "Sustainable", "Nature"],
    [
      "What can reduce plastic waste?",
      "Which problem affects global temperature?",
      "Say 'We should protect the environment'.",
      "Write 3 ways to help the environment.",
      "Is recycling good for society?",
    ]
  ),
  topic(
    "Health & Lifestyle",
    LevelName.INTERMEDIATE,
    [
      "Balanced Diet",
      "Exercise Routines",
      "Sleep and Rest",
      "Stress Management",
      "Mental Health Basics",
      "Healthy Choices",
      "Doctor Advice",
      "Lifestyle Changes",
      "Wellness Goals",
      "Health Review",
    ],
    ["Nutrition", "Exercise", "Sleep", "Stress", "Balanced", "Habits", "Wellness", "Relax", "Diet", "Energy"],
    [
      "What helps your body recover daily?",
      "Which habit supports mental health?",
      "Say 'I try to eat healthy food'.",
      "Write about your healthy habits.",
      "Is regular exercise important?",
    ]
  ),
  topic(
    "Work & Careers",
    LevelName.INTERMEDIATE,
    [
      "Job Applications",
      "CV Vocabulary",
      "Interview Questions",
      "Workplace Communication",
      "Teamwork Skills",
      "Deadlines and Meetings",
      "Career Goals",
      "Part-time Jobs",
      "Professional Email",
      "Careers Review",
    ],
    ["Resume", "Interview", "Colleague", "Deadline", "Salary", "Experience", "Apply", "Skill", "Manager", "Career"],
    [
      "What document lists your work experience?",
      "Who conducts a job interview?",
      "Say 'I am applying for this position'.",
      "Write about your future career goal.",
      "Is teamwork important at work?",
    ]
  ),
  topic(
    "Culture & Traditions",
    LevelName.INTERMEDIATE,
    [
      "Cultural Differences",
      "Traditions Around the World",
      "Festivals and Customs",
      "Food Culture",
      "Greetings Across Cultures",
      "Taboos and Etiquette",
      "National Identity",
      "Art and Heritage",
      "Respectful Communication",
      "Culture Review",
    ],
    ["Tradition", "Custom", "Festival", "Heritage", "Etiquette", "Respect", "Diverse", "Ceremony", "Identity", "Culture"],
    [
      "What word means a long-established practice?",
      "Why is etiquette important?",
      "Say 'I respect different cultures'.",
      "Write about a tradition in your country.",
      "Are customs the same everywhere?",
    ]
  ),
  topic(
    "News & Current Events",
    LevelName.INTERMEDIATE,
    [
      "Headline Vocabulary",
      "Reporting Verbs",
      "Fact vs Opinion",
      "Local News",
      "Global News",
      "Interviewing",
      "Summarizing Articles",
      "Media Sources",
      "Discussing Events",
      "News Review",
    ],
    ["Headline", "Report", "Source", "Event", "Journalist", "Article", "Broadcast", "Update", "Fact", "Opinion"],
    [
      "What is usually the title of a news story?",
      "How do you separate fact from opinion?",
      "Say 'I read the news every morning'.",
      "Summarize a recent event in 3 sentences.",
      "Should news have reliable sources?",
    ]
  ),
  topic(
    "Problem Solving & Advice",
    LevelName.INTERMEDIATE,
    [
      "Describing Problems",
      "Giving Advice",
      "If I Were You",
      "Suggesting Solutions",
      "Agreeing to Help",
      "Polite Suggestions",
      "Role-play Scenarios",
      "Conflict Resolution",
      "Asking for Help",
      "Advice Review",
    ],
    ["Problem", "Solution", "Advice", "Suggest", "Should", "Could", "Help", "Issue", "Recommend", "Support"],
    [
      "Which phrase gives advice politely?",
      "What should you do before suggesting solutions?",
      "Say 'If I were you, I would talk to the teacher'.",
      "Write advice for someone who is stressed.",
      "Is listening important when solving problems?",
    ]
  ),
];

const HARD_TOPICS: TopicCatalogEntry[] = [
  topic(
    "Conditionals & Hypotheticals",
    LevelName.HARD,
    [
      "Zero and First Conditionals",
      "Second and Third Conditionals",
      "Wishes and Hypotheticals",
      "If Clauses",
      "Mixed Conditionals Intro",
      "Unless and Provided",
      "Hypothetical Questions",
      "Regret Expressions",
      "Conditional Practice",
      "Conditionals Review",
    ],
    ["If", "Would", "Had", "Unless", "Wish", "Hypothetical", "Regret", "Possible", "Unreal", "Consequence"],
    [
      "Complete: 'If you freeze water, it ____.'",
      "Which expresses regret about the past?",
      "Say 'I wish I could travel the world'.",
      "Write 2 first and 2 second conditional sentences.",
      "Does second conditional describe real situations?",
    ]
  ),
  topic(
    "Passive Voice & Formal English",
    LevelName.HARD,
    [
      "Introduction to Passive Voice",
      "Formal English Structures",
      "Reported Speech",
      "Active vs Passive",
      "Passive in Academic Writing",
      "Formal Connectors",
      "Impersonal Structures",
      "Official Letters",
      "Scientific Passive",
      "Formal English Review",
    ],
    ["Passive", "Formal", "Reported", "Moreover", "Therefore", "Conducted", "Was written", "Inquire", "Assist", "Nevertheless"],
    [
      "Convert to passive: 'Shakespeare wrote Hamlet.'",
      "Which connector is formal?",
      "Say 'The experiment was conducted carefully'.",
      "Rewrite 3 sentences in passive voice.",
      "Does 'will' become 'would' in reported speech?",
    ]
  ),
  topic(
    "Expressing Opinions & Arguments",
    LevelName.HARD,
    [
      "Giving Opinions",
      "Structuring Arguments",
      "Debate and Discussion Skills",
      "PEEL Method",
      "Rebuttals",
      "Persuasive Language",
      "Counterarguments",
      "Closing Statements",
      "Critical Thinking",
      "Arguments Review",
    ],
    ["Opinion", "Evidence", "However", "Furthermore", "Rebuttal", "Persuade", "Claim", "Counter", "Conclude", "Debate"],
    [
      "Which phrase politely disagrees?",
      "What does P stand for in PEEL?",
      "Say 'In my opinion, education is important'.",
      "Write a short argument using PEEL.",
      "Is a rebuttal a response to the opposing side?",
    ]
  ),
  topic(
    "Advanced Vocabulary",
    LevelName.HARD,
    [
      "Academic Word List Intro",
      "Synonyms and Nuance",
      "Collocations",
      "Word Families",
      "Prefixes and Suffixes",
      "Register Awareness",
      "Precision in Word Choice",
      "Context Clues Advanced",
      "Vocabulary in Context",
      "Advanced Vocab Review",
    ],
    ["Significant", "Implement", "Analyze", "Consequence", "Facilitate", "Nuanced", "Collocation", "Register", "Precise", "Context"],
    [
      "Which word is closest to 'important' in academic writing?",
      "What is a collocation?",
      "Say 'The results were significant'.",
      "Use 3 academic words in sentences.",
      "Does register mean formality level?",
    ]
  ),
  topic(
    "Academic Writing",
    LevelName.HARD,
    [
      "Essay Structure",
      "Thesis Statements",
      "Paragraph Unity",
      "Citing Sources",
      "Avoiding Plagiarism",
      "Academic Tone",
      "Introductions and Conclusions",
      "Cohesion Devices",
      "Editing Strategies",
      "Academic Writing Review",
    ],
    ["Thesis", "Paragraph", "Citation", "Plagiarism", "Cohesion", "Argument", "Evidence", "Draft", "Revise", "Tone"],
    [
      "What sentence states the main argument?",
      "Why must sources be cited?",
      "Say 'This essay discusses climate change'.",
      "Write an introduction with a thesis statement.",
      "Is plagiarism acceptable in academic work?",
    ]
  ),
  topic(
    "Business English",
    LevelName.HARD,
    [
      "Meetings Vocabulary",
      "Negotiation Phrases",
      "Professional Email",
      "Presentations",
      "Agendas and Minutes",
      "Client Communication",
      "Corporate Etiquette",
      "Deal-making Language",
      "Follow-up Messages",
      "Business English Review",
    ],
    ["Agenda", "Negotiate", "Stakeholder", "Proposal", "Deadline", "Follow up", "Client", "Revenue", "Partnership", "Deliverable"],
    [
      "What document outlines meeting topics?",
      "Which phrase opens a professional email?",
      "Say 'Thank you for your prompt response'.",
      "Write a short meeting follow-up email.",
      "Is punctuality important in business?",
    ]
  ),
  topic(
    "Idioms & Expressions",
    LevelName.HARD,
    [
      "Common English Idioms",
      "Idioms in Context",
      "Figurative Language",
      "Cultural Idioms",
      "Idioms at Work",
      "Idioms in Media",
      "Avoiding Literal Translation",
      "Idiom Stories",
      "Phrasal Idioms",
      "Idioms Review",
    ],
    ["Break the ice", "Piece of cake", "Hit the books", "Under the weather", "Once in a blue moon", "Cost an arm and a leg", "Let the cat out", "On the same page", "Rule of thumb", "Call it a day"],
    [
      "What does 'piece of cake' mean?",
      "Which idiom means feeling sick?",
      "Say 'Let's break the ice with introductions'.",
      "Write 3 sentences using idioms correctly.",
      "Should idioms be translated word for word?",
    ]
  ),
  topic(
    "Critical Reading",
    LevelName.HARD,
    [
      "Main Idea and Details",
      "Inference Skills",
      "Author's Purpose",
      "Bias Detection",
      "Text Structure",
      "Evaluating Arguments",
      "Comparing Texts",
      "Annotating Strategies",
      "Reading for Evidence",
      "Critical Reading Review",
    ],
    ["Inference", "Bias", "Purpose", "Evidence", "Claim", "Imply", "Analyze", "Contrast", "Evaluate", "Perspective"],
    [
      "What skill helps you read between the lines?",
      "How do you detect bias?",
      "Say 'The author implies that change is necessary'.",
      "Summarize an article's main idea and evidence.",
      "Is author's purpose always stated directly?",
    ]
  ),
  topic(
    "Nuanced Grammar",
    LevelName.HARD,
    [
      "Subjunctive Mood",
      "Inversion for Emphasis",
      "Cleft Sentences",
      "Ellipsis and Substitution",
      "Advanced Articles",
      "Noun Clauses",
      "Reduced Relative Clauses",
      "Parallel Structure",
      "Grammar in Formal Writing",
      "Nuanced Grammar Review",
    ],
    ["Subjunctive", "Inversion", "Cleft", "Ellipsis", "Parallel", "Clause", "Emphasis", "Formal", "Structure", "Mood"],
    [
      "Which sentence uses inversion for emphasis?",
      "What is parallel structure?",
      "Say 'It was John who solved the problem'.",
      "Write a sentence using a cleft structure.",
      "Does subjunctive appear in formal recommendations?",
    ]
  ),
  topic(
    "Professional Communication",
    LevelName.HARD,
    [
      "Tone in Professional Settings",
      "Giving Feedback",
      "Handling Complaints",
      "Networking Language",
      "Executive Summaries",
      "Cross-team Updates",
      "Clarity and Brevity",
      "Active Listening Phrases",
      "Conflict at Work",
      "Professional Comm Review",
    ],
    ["Feedback", "Clarify", "Stakeholder", "Concise", "Network", "Resolve", "Update", "Align", "Objective", "Professional"],
    [
      "What makes professional communication effective?",
      "How should feedback be delivered?",
      "Say 'Could you clarify the deadline, please?'",
      "Write a professional status update.",
      "Is active listening part of communication?",
    ]
  ),
  topic(
    "Literature Analysis",
    LevelName.HARD,
    [
      "Plot and Character",
      "Theme and Motif",
      "Symbolism",
      "Narrative Voice",
      "Setting and Mood",
      "Literary Devices",
      "Quoting Literature",
      "Comparing Characters",
      "Short Story Analysis",
      "Literature Review",
    ],
    ["Theme", "Symbolism", "Protagonist", "Motif", "Narrator", "Setting", "Metaphor", "Conflict", "Irony", "Plot"],
    [
      "What is a recurring idea in a story called?",
      "Who is the main character?",
      "Say 'The theme explores friendship and loss'.",
      "Analyze a character in 4 sentences.",
      "Can setting affect mood?",
    ]
  ),
  topic(
    "Scientific English",
    LevelName.HARD,
    [
      "Lab Report Structure",
      "Hypothesis Language",
      "Methodology Vocabulary",
      "Data and Results",
      "Scientific Passive",
      "Units and Measurements",
      "Cause and Effect in Science",
      "Research Questions",
      "Abstract Writing",
      "Scientific English Review",
    ],
    ["Hypothesis", "Method", "Variable", "Results", "Conclusion", "Data", "Experiment", "Analyze", "Measurement", "Abstract"],
    [
      "What section describes how an experiment was done?",
      "Which tense is common in scientific methods?",
      "Say 'The results were analyzed using software'.",
      "Write a hypothesis for a simple experiment.",
      "Should an abstract summarize the whole report?",
    ]
  ),
  topic(
    "Legal & Formal Language",
    LevelName.HARD,
    [
      "Legal Terms Intro",
      "Contracts Vocabulary",
      "Rights and Obligations",
      "Formal Notices",
      "Disclaimer Language",
      "Precision in Legal English",
      "Shall vs Will",
      "Definitions Sections",
      "Compliance Terms",
      "Legal English Review",
    ],
    ["Contract", "Clause", "Liability", "Obligation", "Compliance", "Hereby", "Pursuant", "Jurisdiction", "Binding", "Terms"],
    [
      "What document sets legal obligations?",
      "Why is precision important in legal English?",
      "Say 'The parties hereby agree to the terms'.",
      "Explain a rights and obligations clause.",
      "Is 'shall' common in formal legal texts?",
    ]
  ),
  topic(
    "Persuasive Writing",
    LevelName.HARD,
    [
      "Persuasive Techniques",
      "Audience Awareness",
      "Emotional Appeals",
      "Logical Appeals",
      "Call to Action",
      "Rhetorical Questions",
      "Counterclaim Handling",
      "Speech Writing",
      "Editorial Structure",
      "Persuasive Writing Review",
    ],
    ["Persuade", "Audience", "Appeal", "Rhetorical", "Call to action", "Counterclaim", "Convince", "Tone", "Ethos", "Pathos"],
    [
      "What is a call to action?",
      "Which appeal uses logic and evidence?",
      "Say 'We must act now to protect our future'.",
      "Write a persuasive paragraph with a call to action.",
      "Should persuasive writing address counterclaims?",
    ]
  ),
  topic(
    "Cross-cultural Communication",
    LevelName.HARD,
    [
      "Cultural Intelligence",
      "High vs Low Context Cultures",
      "Nonverbal Communication",
      "Avoiding Miscommunication",
      "Global Teams",
      "Inclusive Language",
      "Cultural Assumptions",
      "Adapting Communication Style",
      "International Negotiation",
      "Cross-cultural Review",
    ],
    ["Culture", "Context", "Inclusive", "Assumption", "Adapt", "Global", "Nonverbal", "Miscommunication", "Diverse", "Respect"],
    [
      "What is high-context communication?",
      "Why is inclusive language important?",
      "Say 'I appreciate different perspectives'.",
      "Write about adapting style in global teams.",
      "Can nonverbal cues differ across cultures?",
    ]
  ),
];

export const TOPIC_CATALOG: Record<LevelName, TopicCatalogEntry[]> = {
  [LevelName.BASIC]: BASIC_TOPICS,
  [LevelName.INTERMEDIATE]: INTERMEDIATE_TOPICS,
  [LevelName.HARD]: HARD_TOPICS,
};

export function getTopicsForLevel(level: LevelName): TopicCatalogEntry[] {
  return TOPIC_CATALOG[level];
}
